### ISSUE TITLE
Make it easier for users to migrate their service to GOV.UK Frontend

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#1162]
## What

Create documentation that helps teams with existing services migrate to GOV.UK Frontend.

## Why

This will help drive adoption and improve the consistency and accessibility of older services.

## Stories

- [ ] Provide guidance on how to migrate to GOV.UK Frontend [#892](https://github.com/alphagov/govuk-design-system/issues/892)
- [ ] publish migration case studies
- [ ] expose internal Sass variables and mixins
- [ ] make it easier to do a gradual migration
