### ISSUE TITLE
Improve macros in GOV.UK Frontend

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#1386]
## Related stories and issues

- [ ] Make it easier to add a hint or an error message to a fieldset #1166
- [ ] Tables: Consider enabling array iteration in macros #570
- [ ] Add an icon next to an input using the govuk Input macro #924
- [ ] Allow details component to be callable #941
- [x] Date input does not allow attributes to be passed to the fieldset #1478
- [ ] Add label or legend param to date-input #1155 
- [ ] Macro documentation is confusing [#930](https://github.com/alphagov/govuk-design-system/issues/930)
- [x] Test for empty items in radios and checkboxes [#1494](https://github.com/alphagov/govuk-frontend/issues/1494)
- [ ] Radios and checkboxes with empty conditionals causes odd spacing #1546
- [ ] Provide a way to import all macros #1278

**Comment by nickcolley** [comment]
I've documented a potential spike that could help us understand improvements to macros:

https://github.com/alphagov/govuk-frontend/issues/1669

**Comment by 36degrees** [comment]
Closing in favour of the nunjucks label.
