### ISSUE TITLE
Improve documentation of GOV.UK Frontend

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#1388]
## What

- identify documentation improvements that would help users to migrate to GOV.UK Frontend
- establish a sustainable process for writing and reviewing technical documentation
- test the hypothesis that publishing Frontend docs in the tech docs format will make them easier to find and use
- publish updated documentation

## Why

We know that there are gaps in our documentation for GOV.UK Frontend, which make it harder for people to migrate to it.

## Stories

- [x] Audit all our guidance and documentation - #125
- [x] Discovery exercise on user needs around migration - #126
- [x] Factfinding research into user needs around migration - #127
- [x] Create new migration guidance (draft for research) [#2](https://github.com/alphagov/govuk-frontend-docs/pull/2)
- [x] Test draft of new migration guidance [#255](https://github.com/alphagov/design-system-team-internal/issues/255)
- [x] Create and publish migration guidance [#2](https://github.com/alphagov/govuk-frontend-docs/pull/2)

## Related stories

- [ ] Review the Nunjucks configuration we expect users to use - #950
- [ ] Check for broken links in markdown files - #755
- [x] Explain why we have a different browser matrix than the service manual - #1026
- [x] Add bundler instructions for rollup - #866
- [ ] Documentation on how to load the assets with webpack - #1071
- [x] Provide guidance on how to migrate to GOV.UK Frontend - [#892](https://github.com/alphagov/govuk-design-system/issues/892)
- [ ] publish migration case studies
- [x] Sass mixins, functions and variables are not publicly documented #1634
- [ ] make it easier to do a gradual migration
- [ ] add guidance on changing the font and colours - [#1019](https://github.com/alphagov/govuk-design-system/issues/1019)

**Comment by 36degrees** [comment]
Closing in favour of the documentation label
