### ISSUE TITLE
Improve how JavaScript works in GOV.UK Frontend

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#1389]
## What
We know there are issues with our current JavaScript setup, code and tooling which we should improve. Some of this work will help us unlock future work, i.e: more complex components (like modals) and supporting translations.

### Preliminary work

- [x] https://github.com/alphagov/govuk-frontend/issues/2478

### Internationalisation
Allow strings in our component JavaScript to be customised, to allow for text in other languages (eg: Welsh).

- [x] https://github.com/alphagov/govuk-frontend/issues/1708 

### Reduce Internet Explorer support
We're [aiming to reduce IE support](https://github.com/alphagov/govuk-frontend/discussions/2607) in future major versions of GOV.UK Frontend.

- [x] https://github.com/alphagov/govuk-frontend/issues/2503 
- [ ] https://github.com/alphagov/govuk-frontend/issues/2621

### Figure out what our component JavaScript should look like and how it should behave
We should consider how we handle modern JavaScript features, typing, public and private properties, event listening, state management, styling, interactions with apps and third-party frameworks, and our component API.

- [x] https://github.com/alphagov/govuk-frontend/issues/1722
- [x] https://github.com/alphagov/govuk-frontend/issues/711

### Document our JavaScript
We need to figure out what our documentation will look like, and we need to actually publish that documentation.

- [x] https://github.com/alphagov/govuk-frontend/issues/1722 (duplicate)
- [x] https://github.com/alphagov/govuk-frontend/issues/2563
- [x] https://github.com/alphagov/govuk-frontend/issues/2564

### Improve tooling

- [x] https://github.com/alphagov/govuk-frontend/issues/2558
- [x] https://github.com/alphagov/govuk-frontend/issues/2717

### Improve testing
- [x] https://github.com/alphagov/govuk-frontend/issues/2559
- [ ] https://github.com/alphagov/govuk-frontend/issues/2502

## Resources
- [Architectural changes project board](https://github.com/orgs/alphagov/projects/41/views/1)
- [JavaScript planning Mural board](https://app.mural.co/invitation/mural/gaap0347/1641473099122?sender=u1bcfe02220a3ea53a47f4733&key=314708ce-9463-4ccd-a5aa-c3c864c6e88a)
- [2022-10-11: Components configuration](https://docs.google.com/presentation/d/185vjW_mLSMeGM-DibWcvfmkl0TnwFTXrMNMkI8SFZ48/edit#slide=id.g10d42026b8_2_0)
- [2021-10-06: What on earth is this 'JavaScript work' we keep talking about?](https://docs.google.com/presentation/d/1FPaDB0brW_qTqD8TQQPjX6pQx1gDAm-2SAc4Vs52Mn8/edit#slide=id.gf61866d04a_0_15)
- [2020-11-23: "Future of GOV.UK Frontend" exercise](https://docs.google.com/spreadsheets/d/1778vKUhbBufIxNSixGD9E5NafhU1jFAy7vfzTmvHi5o/edit#gid=777595173)

**Comment by frankieroberto** [comment]
@timpaul might be worth adding that the Character Count component also has hardcoded English text (see [code](https://github.com/alphagov/govuk-frontend/blob/master/src/components/character-count/character-count.js#L175-L178)), and so whichever solution is proposed for translation can be adopted there too?

**Comment by kellylee-gds** [comment]
Previous body of issue:

## Goal
We can publish more complex components involving JavaScript, in a consistent way that can be adopted by service teams.

## Why
Doing this work allows us to publish more complex components like modal dialogue and autocomplete, both of which we know are needed by users.

## Related stories

- [ ] Allow ErrorSummary component to disable autofocus #1068
- [ ] Cannot import standard ES6 modules from npm #711
- [ ] Accordion has hardcoded English text in javascript file #1325
- [x] Expose better ways to set values on components (https://github.com/alphagov/govuk-frontend/issues/1028)
- [ ] Investigate components being initialised more than once #1127

**Comment by owenatgov** [comment]
JS Squad to decide which of the epics in this card to work on at the present moment in time and move them into the epics column.

**Comment by 36degrees** [comment]
Closing this as the scope is too broad to be useful at the minute (there's always more we can do to improve!) and the few remaining stories are better covered in other epics (or are epics themselves):

- #3478
- #2621
- #2502
