### ISSUE TITLE
Improve tooling of GOV.UK Frontend

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#1390]
## Stories

- [ ] Review application can mislead if a component is polyfilled #674
- [ ] Ensure release-to-branch script fails gracefully when running build #1098 
- [ ] Test that documented component options match the templates #1139
- [ ] Design System does not build in Windows environment #598

**Comment by 36degrees** [comment]
Closing this in favour of the tooling label.
