### ISSUE TITLE
Test the usability of GOV.UK Frontend 3.0

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#1427]
## What

We need to run a run a round of lab-based research on a prototype that uses GOV.UK Frontend 3.0.

## Why

The DAC report has given us confidence that GOV.UK Frontend 3.0 will meet WCAG 2.1 AA. 

However, we also need to verify that the proposed design changes are usable - in particular the updated focus styles. 

## Stories

- [x] Recruit participants for a round of research on GOV.UK Frontend 3.0   #1429
- [x] Build a user research prototype to test GOV.UK Frontend 3.0  #1428
- [x] Run a round of user research on GOV.UK Frontend 3.0  #1430
- [x] Analyse user research on GOV.UK Frontend 3.0  #1431

## Optional bonus...

It’s also worth considering the possible future value of this prototype, as a tool for testing design changes, doing user research, delivering training or providing examples.

**Comment by kellylee-gds** [comment]
Completed and moved to done
