### ISSUE TITLE
Release GOV.UK Frontend v3.4.0 🚀

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1632]
Release [GOV.UK Frontend v3.4.0](https://github.com/alphagov/govuk-frontend/milestone/28), following our [release process](https://github.com/alphagov/govuk-frontend/blob/master/docs/contributing/publishing.md).

## Done when:

- [x] Release notes compiled
- [x] Release notes reviewed
- [x] Package published
- [x] Release communicated on Slack
- [x] [Sprint board](https://github.com/orgs/alphagov/projects/4) updated

## Then: 
- [ ] [Update the Design System to use Frontend v3.4.0](https://github.com/alphagov/govuk-design-system/issues/1080)
- [ ] [Update the Prototype Kit to use Frontend v3.4.0](https://github.com/alphagov/govuk-prototype-kit/issues/833)
- [ ] [Release a new version of the Prototype Kit](https://github.com/alphagov/govuk-prototype-kit/issues/834)
