### ISSUE TITLE
Improvements to the header component

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1679]
The header needs to be more flexible – for example, it should allow for just having one navigational link without that link ending up in a menu on mobile; it should allow custom HTML so that you can include a sign out button (styled as a link).

There might be things we can do to make the header more useful in other contexts - eg, full-width, departmental, admin, caseworking systems, etc.

## Stories

- [ ] Header should support a single link without collapsing to a menu on mobile #1635 
- [ ] Header Component - Custom HTML option for links #1573
- [ ] Product name wraps onto new line with non full-width header #1502
- [ ] Review if `aria-label` in header navigation is necessary #1340
- [ ] 'Unlabelled graphic' read out within header using NVDA #1636
- [ ] Make it possible to override or remove the Crown logotype from the header #1639

**Comment by nickcolley** [comment]
We caught up with Max and Ian from GOV.UK Publishing and agreed that they should review our proposed changes to the header (and footer) to ensure it makes sense for their use case.

**Comment by vanitabarrett** [comment]
@36degrees Just wanted to check - does this include https://github.com/alphagov/govuk-frontend/issues/1904 ? It came up in the Friday call today and I wasn't sure if it was included in this work as it has been split out from https://github.com/alphagov/govuk-frontend/issues/1682

**Comment by 36degrees** [comment]
Closing this as having an epic for the component isn't currently useful for us.
