### ISSUE TITLE
Improvements to the footer component

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1680]
The footer has a number of (~minor) layout issues that are hard to address without making changes to the markup. It also has a number of hardcoded English strings which we should address, aligning with supporting multiple languages.

Some of these fixes will involve making breaking changes.

## Stories

- [ ] Long text in footer columns do not wrap #1647
- [ ] Footer layout isn't aligned with content layout #1539
- [ ] Safari alignment issue with Footer list containing odd number of items #1284
- [ ] Add ability to override or remove OGL logo in Footer #1291
- [ ] Add ability to override or remove Crown Copyright in Footer #1290

**Comment by DouglasCaven** [comment]
The new version of the Axe Review accessibility tool has highlighted a potential issue suggesting the ‘Crown copyright’ logo in the footer must have sufficient colour contrast. The failure is actually the logo and the colour of text passed and thought it should be noted.

**Comment by CharlotteDowns** [comment]
## The problem
![current Crown copyright logo in the footer](https://user-images.githubusercontent.com/56260216/106613192-d7b30980-6561-11eb-8f5b-9ffa8df5c47d.jpg)
The crown copyright logo has a hex code colour of `#6E777A`, which against the footer background of `#F3F2F1` has a AA Large 4.09:1 colour contrast ratio. 


## A potential fix
![Crown copyright logo in the footer using the darker text colour](https://user-images.githubusercontent.com/56260216/106612745-578ca400-6561-11eb-9b1e-a2255c12ea56.jpg)
Here is a mock-up of the crown copyright logo using the footer text colour `#454A4C` which has a contrast ratio of AAA 8.03:1 against the footer background `#F3F2F1`.

This approach may not meet the brand use of the Crown copyright logo and should be looked into.

**Comment by 36degrees** [comment]
Closing this as having an epic for the component isn't currently useful for us.
