### ISSUE TITLE
Improve support for different Sass compilers

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1685]
GOV.UK have [flagged that our Sass is slow to compile](https://github.com/alphagov/govuk-frontend/issues/1671). Although this mostly affects ruby-sass, which is [deprecated](https://sass-lang.com/ruby-sass), it has a [noticeable effect in other compilers too](https://github.com/alphagov/govuk-frontend/issues/1671#issuecomment-565531674).

Doing this should also help improve the workflow in the review app as it’ll make reloads faster.
We might also want to consider finding a way to benchmark / set up a budget for this so that we don’t accidentally make it slower again in the future.

This will probably involve making breaking changes, so we should plan it as part of GOV.UK Frontend 4.0.

Related, we should consider setting up tests that make sure that GOV.UK Frontend works with the various different Sass compilers, and ideally define the minimum versions that we expect GOV.UK Frontend to support, and understand what features we can therefore use.

## Stories

- [x] Be explicit about which Sass compilers we support #1683
- [x] Fail the build if compilation fails with any of our supported Sass compilers #1684
- [x] Media query with $until fails #1674
