### ISSUE TITLE
Move GOV.UK Frontend docs to Tech Docs Template

### ISSUE THREAD

**Issue by m-green** [alphagov/govuk-frontend#1694]
## What
After improvements from research and analysis, publish Frontend docs as a Tech Docs Template (TDT) site.

## Stories

- [x] Agree domain names for the Frontend and Prototype Kit sites https://github.com/alphagov/design-system-team-internal/issues/235
- [x] Set up continuous deployment of the master branch https://github.com/alphagov/govuk-frontend-docs/issues/6
- [x] [Deploy Tech Docs Template site](https://github.com/alphagov/design-system-team-internal/issues/236)
