### ISSUE TITLE
Improve the date input component

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#1695]
## What
Make various improvements to the accessibility and usability of the date input component.

## Why
This work forms part of our continuous improvement mission. The date input component is one of our most used and we have numerous outstanding stories and issues relating to it.

## Stories

- [x] Investigate removing `role=“group”` from date input fieldset #1590
- [x] date-input: id documented as optional but required to create hintId and errorId 
#1557
- [x] Investigate alternative to [type=number] for the date input component #1449
- [x] NVDA not assigning labels properly in date input component #1408
- [ ] Add label or legend param to date-input #1155 
- [ ] Pass values to date-input when using default items #1154
- [x] Dragon Accessibility issue with DOB field #1101
- [x] Clarify 'Date Input' error messages https://github.com/alphagov/govuk-design-system/issues/868
- [x] Add Dragon bug to date input guidance (close) https://github.com/alphagov/govuk-design-system/issues/782

**Comment by 36degrees** [comment]
Closing this as we can now track issues related to specific components using labels. Both of the stories that are still open have the `date input` label.
