### ISSUE TITLE
Update the date input to use text inputs with a numeric input mode

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1700]
## What

Update the date input so that each of the inputs is of `type="text"` with `inputmode="numeric"`, rather than using `type="number"`.

For now, we're going to keep the `pattern` attribute as it ensures the right keyboard is displayed for iOS < 12.2+ – we can review this when we stop seeing much traffic from these older versions.

## Why 

For context, see the results of the investigation in #1449 

## Who needs to know about this

Developers

## Done when

- [ ] Inputs within the date input component use `type="text"`
- [ ] Inputs within the date input component use `inputmode="numeric"`
- [ ] Tests for the above
- [ ] Tested in the browsers / assistive technologies that we support

We should then:

- [ ] Verify that https://github.com/alphagov/govuk-frontend/issues/1101 is fixed and close it
- [ ] Close https://github.com/alphagov/govuk-design-system/issues/782
- [ ] Verify that https://github.com/alphagov/govuk-frontend/issues/1408 is fixed and close it
- [ ] Remove "Attribute pattern is only allowed when the input type is email, password, search, tel, text, or url" from our [list of known errors / warnings](https://github.com/alphagov/govuk-frontend/issues/1280#issuecomment-509588851) as we are now be using `input type="text"` which won't trigger validation warnings.

**Comment by 36degrees** [comment]
@htmlandbacon has started working on this in #1527 – I've asked him if he's happy to make some changes to the PR, and we can pick this up next week.
