### ISSUE TITLE
Allow users to override hardcoded strings in our component JavaScript (internationalisation)

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1708]
## What
Allow strings in our component JavaScript to be customised/changed, to allow for text in other languages, e.g: Welsh.

## Why
Some service teams have a requirement to provide their services in Welsh as well as English (and other teams support a wider range of language translations too). At the moment, service teams are stuck with some elements of the page in English unless they manually copy our JavaScript into their application, which isn't ideal. 

Related issues:

- https://github.com/alphagov/govuk-frontend/issues/1681
- https://github.com/alphagov/govuk-frontend/issues/2094
- https://github.com/alphagov/govuk-frontend/issues/1904
- https://github.com/alphagov/govuk-frontend/issues/1325
- https://github.com/alphagov/govuk-frontend/issues/1291
- https://github.com/alphagov/govuk-frontend/issues/1290
- https://github.com/alphagov/govuk-frontend/issues/2568

This work is also closely related to how we allow users to set and configure JavaScript options. We should keep in mind that it may be simpler to develop a solution for internationalisation that also works for setting all configurable JavaScript options.

## Who needs to know about this
Developers; Tech Writer

### Prep & Research

- [x] https://github.com/alphagov/govuk-frontend/issues/1709
- [x] https://github.com/alphagov/govuk-frontend/issues/1714
- [x] https://github.com/alphagov/govuk-frontend/issues/2566
- [x] https://github.com/alphagov/govuk-frontend/issues/1715
- [x] https://github.com/alphagov/govuk-frontend/issues/2736
- [x] https://github.com/alphagov/govuk-frontend/issues/2780
- [x] https://github.com/alphagov/govuk-frontend/issues/2781

### Missing Nunjucks translations
- [x] https://github.com/alphagov/govuk-frontend/pull/2702
- [x] https://github.com/alphagov/govuk-frontend/issues/1904
- [x] https://github.com/alphagov/govuk-frontend/issues/2687
- [x] https://github.com/alphagov/govuk-frontend/issues/2690
- [x] https://github.com/alphagov/govuk-frontend/issues/2692

### Translating hardcoded strings in JS 

- [x] https://github.com/alphagov/govuk-frontend/issues/2801
- [x] https://github.com/alphagov/govuk-frontend/issues/2699
- [x] https://github.com/alphagov/govuk-frontend/issues/2698
- [x] https://github.com/alphagov/govuk-frontend/issues/2802
- [x] https://github.com/alphagov/govuk-frontend/issues/2700
- [x] https://github.com/alphagov/govuk-frontend/issues/2804
- [x] https://github.com/alphagov/govuk-frontend/issues/2701
- [x] https://github.com/alphagov/govuk-frontend/issues/2805
- [x] https://github.com/alphagov/govuk-frontend/issues/2829

### Documentation
- [x] https://github.com/alphagov/govuk-design-system/issues/2307
- [x] https://github.com/alphagov/govuk-frontend-docs/issues/196
- [x] https://github.com/alphagov/govuk-frontend/issues/2749

## Stretch Goals
- [ ] https://github.com/alphagov/govuk-frontend/issues/1127
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/203

**Comment by natcarey** [comment]
At HMRC we only have one component which requires this, we've implemented it with `data-` attributes.  The Nunjucks component takes arguments for the content and passes them through to the JS via the dom element which gets instantiated.

The component which does this is a pure JS component which is activated by a custom meta tag.  https://github.com/hmrc/hmrc-frontend/blob/master/src/components/timeout-dialog/template.njk

I'd suggest that the user of a component shouldn't need to know which content is produced by JS and which isn't.  Providing them all via the component parameters is my attempt to achieve that.

**Comment by jamesalfei** [comment]
At DVLA, we require frontend component localisation for supporting the welsh language. This is, in most cases, done within our application but on components such as the text area character count, this is done within the GOVUK frontend via Javascript. This means we cannot localise the text on these components.

This issue was present in 2018 when a PR was opened (and subsequently declined) in favour of a more common approach: https://github.com/alphagov/govuk-frontend/pull/1038

This consistent approach across all components will allow localisation and allow us to offer our customers fully internationalised pages, rather than a mix of Welsh and English which we currently have due to this component.

Note, we are fully aware that we can bring the code in-house and modify it to our needs, but this would mean more overhead to keep up to date with the centralised repo. This is something we want to try and avoid if at all possible.

**Comment by domoscargin** [comment]
Re: prioritsation of config passed by data attributes and config passed by JavaScript, we've decided that data attributes should always take precedence over config passed by JavaScript.

https://github.com/alphagov/govuk-frontend/issues/2781

**Comment by 36degrees** [comment]
I'm calling this done – the only unticked items are only tangentially unrelated.
