### ISSUE TITLE
Decide and document our JavaScript conventions for components

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1722]
## What
Decide and document our JavaScript conventions for GOV.UK Frontend components. At the moment, our JavaScript has some undocumented conventions (e.g: `init` methods) which we should document. We should also think about conventions that we don't have in place yet, for example:

- public vs private methods
- conventions for triggering and/or listening to events
- managing state

We need to keep in mind that these conventions should work for future components we build, especially more complex ones like modals. Modals have more unique functionality, e.g: how do you initialise/manage more than one per page; how do users hook into the open/close?

## Why
In our component JavaScript at the moment, we don't have a concept of private vs public methods. Doing this will:

- make it possible for users to control some behaviour of components from their application (e.g: https://github.com/alphagov/govuk-frontend/issues/1677)
- make it easier for users to understand which JS methods/variables it is recommended they access in their application script.
- make it easier for us to understand which changes to our JavaScript will affect users and which changes should be considered breaking ones

Having any 'accidental'/unintentional conventions documented will mean we're more likely to follow them in future when building new components or making changes to existing component JavaScript.

## Related issues

- https://github.com/alphagov/govuk-frontend/issues/1677 
- https://github.com/alphagov/govuk-frontend/issues/1530

## Who needs to know about this
Developers; Tech Writer

## Done when

- [x] https://github.com/alphagov/govuk-frontend/issues/1719
- [x] https://github.com/alphagov/govuk-frontend/issues/1720
- [ ] Decide if we need to write this up as a proposal and share with the community first
- [ ] https://github.com/alphagov/govuk-frontend/issues/1721
- [ ] https://github.com/alphagov/govuk-frontend/issues/2560

**Comment by 36degrees** [comment]
Closing, although we should make sure we're including this as part of our 'done when' criteria other JavaScript related work
