### ISSUE TITLE
Move away from sass-lint

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1740]
## What
Move from sass-lint to style-lint (using the config defined in [stylelint-config-gds](https://github.com/alphagov/stylelint-config-gds)). GOVUK have done the bulk of the work for us, and we want the two to be aligned.

## Why

We're currently using sass-lint (via gulp-sass-lint) which is unmaintained since October 2017.

This means that sass-lint will not be kept up to date with changes in CSS or Sass syntax, which may cause us problems in the future.

If any security issues are discovered in sass-lint or any of its dependencies, it will not be updated to address them.

## Done when:

- [x] [Linting rules are published for other projects to use if they want](https://github.com/alphagov/govuk-frontend/issues/1256)
- [x] [Review the rule differences from sass-lint](https://github.com/alphagov/govuk-frontend/issues/1897)
- [x] [Add declaration-no-important](https://github.com/alphagov/stylelint-config-gds/pull/4)
- [x] [Remove sass-lint](https://github.com/alphagov/govuk-frontend/issues/1898)
- [x] [Review the PR to switch from sass-lint to stylelint](https://github.com/alphagov/govuk-frontend/issues/1896)

**Comment by nickcolley** [comment]
We should consider adopting https://github.com/alphagov/scss-lint-govuk

**Comment by nickcolley** [comment]
Actually that seems to be a Ruby project, perhaps: https://stylelint.io/ as recommended by them.

**Comment by nickcolley** [comment]
Had a look into stylelint, looks like it requires a lot of configuration so we'd have to poke around with different rules.

Some of it's automatic fixes would be problematic.

https://github.com/alphagov/govuk-frontend/compare/spike-stylelint?expand=1

**Comment by 36degrees** [comment]
Taking this (and child issues) out of the 3.9.0 milestone whilst we wait on https://github.com/alphagov/govuk-frontend/pull/1875#issuecomment-685034600.
