### ISSUE TITLE
Create notification banner component

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1935]
## What

Create the [notification banner component](https://deploy-preview-1313--govuk-design-system-preview.netlify.app/components/notification-banner/) in GOV.UK Frontend.

## Why

Having reviewed the feedback from the working group, we now need to build the component in Frontend ready for release.

## Depends on

- #1933 
- #1934 

## Further detail

Some specific bits of feedback worth considering from the working group and [accessibility clinic findings](https://github.com/alphagov/govuk-design-system-backlog/issues/2#issuecomment-673356072):
- it’s recommended we remove `aria-labelledby` from the markup for the red and the green banners as they’re not landmarks (https://www.w3.org/TR/wai-aria-1.1/#landmark_roles) and therefore the label will never be read out (the same actually applies to our current error summary)
- we should explain the accessibility considerations – for example what the `role=` does – in comments in the code and/or tests.

## Done when…

- [x] Nunjucks template / macro created based on the API agreed in #1933 
- [x] Tests for Nunjucks template
- [x] Tech docs reviewed by tech writer
- [x] Add styling for notification banner
- [x] Component auto focuses when using role="alert"
- [x] Tests for component auto focus JS
- [x] Finalise notification banner macro options docs #1997 
- [x] Cross-browser tested
- [x] Create some realistic example pages to present at the accessibility clinic #1999
- [x] Take finalised version to accessibility clinic for testing #1999
- [x] Test notification banner with assistive technologies #2010
- [x] Address notification banner accessibility concerns #2011
- [x] Remove error type banner #2030

**Comment by hannalaakso** [comment]
I'm thinking that one thing we should highlight at the accessibility clinic is the approach of making the `<p>` tags look like headings when we have just a single line of content in the banner. We do this as we want to draw attention to the message in the banner and semantically you should haven't a heading tag that doesn't act as a heading for some content below it. However it'd be good to confirm that this isn't a concern as we're making an element look like another element.
