### ISSUE TITLE
Improve inconsistent screenreader behaviours for error summary/notification banner  

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2059]
## What
The error summary and notification banner components are implemented in similar ways: using `role=‘alert’`, `aria-labelledby` and moving focus to the component with JavaScript. However, in our own testing and testing done by others, we have noticed that screenreader behaviour when announcing these components is extremely inconsistent ([link to testing spreadsheet here](https://docs.google.com/spreadsheets/d/1KrgPdKf8M6zsNZcRPUG0r7H1-1aREW5QgnjhhfVHIag/edit?usp=sharing)).

We could investigate the following as some starting points:

- [ ] Test if we can reliably and consistently reproduce any of the issues below 
- [ ] Whether we're using `role='alert'` and `aria-labelledby` in the correct way
- [ ] If there are any other solutions to this problem that perform more consistently
- [ ] If the behaviour of `aria-live` / `role='alert'` is adequately defined in the specs

## Context
When building the notification banner component, it was flagged that `aria-labelledby` was redundant for the error summary component (and therefore on the alert versions of the notification banner too). However, when we tested this in various assistive tech, we found that removing `aria-labelledby` could 1) change the behaviour a lot (especially in Voiceover on Mac), and 2) in general, announcing of error summary/notification banner is extremely inconsistent between different screenreaders. 

In the short term, we decided not to remove aria-labelledbyfrom the error summary, and instead to add aria-labelledby to notification banners to make them consistent with the error summary.

## Related Issues

- [Inconsistent announcing of error summary/notification banner](https://github.com/alphagov/govuk-frontend/issues/1954)
- [Error summary is not focused correctly on second form submission with NVDA](https://github.com/alphagov/govuk-frontend/issues/2055)
- Links within error summary are not consistently read out (Safari + Voiceover on MacOS Catalina) - [Zendesk ticket](https://govuk.zendesk.com/agent/tickets/4315309)

This W3C issue is also slightly related and something we may want to follow up on if we think that the aria properties we're using need to be better defined in the spec, i.e: how things *should* behave on page load: https://github.com/w3c/aria/issues/1360
