### ISSUE TITLE
Release v4.0.0 of GOV.UK Frontend

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-frontend#2274]
## What
Do a major release of prioritised breaking changes in GOV.UK Frontend.

## Who needs to know about this
The whole team

## Done when

- [x] https://github.com/alphagov/govuk-frontend/issues/2193
- [x] https://github.com/alphagov/govuk-frontend/issues/2341
- [x] https://github.com/alphagov/design-system-team-internal/issues/516
- [x] https://github.com/alphagov/govuk-design-system/issues/1934
- [x] https://github.com/alphagov/govuk-frontend/issues/1958
- [x] https://github.com/alphagov/govuk-frontend/issues/2351
- [x] https://github.com/alphagov/design-system-team-internal/issues/515
- [x] https://github.com/alphagov/design-system-team-internal/issues/518
- [x] https://github.com/alphagov/govuk-design-system/issues/1890
- [x] https://github.com/alphagov/design-system-team-internal/issues/519

### Header
- [x] [Review if aria-label in header navigation is necessary](https://github.com/alphagov/govuk-frontend/issues/1340)
- [x] [Decided to do this as part of #1739 as they both touch the same area of code - Document fallback image change to header in 4.0 release notes](https://github.com/alphagov/govuk-frontend/issues/2360)

### Footer
- [x] [Improve the layout options for the footer component](https://github.com/alphagov/govuk-frontend/issues/1726)
- [x] [Footer layout isn't aligned with content layout](https://github.com/alphagov/govuk-frontend/issues/1539)

### Removing deprecated things
- [x] [Remove deprecated main-wrapper mixins](https://github.com/alphagov/govuk-frontend/issues/1379)
- [x] [Remove deprecated $govuk-border-width-form-element-error setting](https://github.com/alphagov/govuk-frontend/issues/1871)
- [x] [Remove govuk-tag--inactive class](https://github.com/alphagov/govuk-frontend/issues/1757)
- [x] [Remove deprecated iff Sass function](https://github.com/alphagov/govuk-frontend/issues/1771)

### Hints and error messages
- [x] [Consider updating hints and error messages to use paragraphs](https://github.com/alphagov/govuk-frontend/issues/2083)
- [x] [Remove display:block hint style as we're switching from span to div](https://github.com/alphagov/govuk-frontend/issues/1856)

### Accordion
- [x] [Update Accordion design](https://github.com/alphagov/govuk-frontend/pull/2257)
- [x] [Update docs to explain that accordion summary line can only contain phrasing content](https://github.com/alphagov/govuk-frontend/issues/2310)

### ID contains special characters
- [x] [Conditional reveals fail if ID contains characters that have a special meaning in CSS](https://github.com/alphagov/govuk-frontend/issues/1808)
- [x] [Character count fails if ID contains characters that have a special meaning in CSS](https://github.com/alphagov/govuk-frontend/issues/1809)

### Other
- [x] [Difficult to notice when cookie banner HTML classes are missing](https://github.com/alphagov/govuk-frontend/issues/2358)
- [x] [Invalid nesting of elements in summary list when actions are included on some but not all rows (WCAG 2.1 4.1.1 Parsing)](https://github.com/alphagov/govuk-frontend/issues/1806)
- [x] [Fix bugs with radios and checkboxes where multiple modules have the same name](https://github.com/alphagov/govuk-frontend/pull/2255)
- [x] [JavaScript modules are attached to the same global variable when imported individually](https://github.com/alphagov/govuk-frontend/issues/1836)
- [x] [After clicking "Skip to main content", focus isn't sent to the content so screenreader can't read from there](https://github.com/alphagov/govuk-frontend/issues/2187)

If the release notes aren't already too long;
- [x] [Remove dependency imports from files in the core and overrides layers](https://github.com/alphagov/govuk-frontend/issues/1800)
- [x] [Move template from the core layer to the objects layer](https://github.com/alphagov/govuk-frontend/issues/1799)

## Design System

- [x] [Design System milestone](https://github.com/alphagov/govuk-design-system/milestone/6)

## Prototype Kit
- [x] [Prototype Kit milestone](https://github.com/alphagov/govuk-prototype-kit/milestone/23)

## Release Steps
- [x] https://github.com/alphagov/govuk-design-system/issues/1889
- [x] https://github.com/alphagov/govuk-frontend/issues/2352
- [x] https://github.com/alphagov/govuk-frontend/issues/2331
- [x] https://github.com/alphagov/govuk-frontend/issues/2314
- [x] Draft release notes for the Prototype Kit
- [x] https://github.com/alphagov/govuk-design-system/issues/1851
- [x] https://github.com/alphagov/govuk-prototype-kit/issues/1063
- [x] https://github.com/alphagov/govuk-frontend/issues/2330
- [x] Release the Prototype Kit
- [x] https://github.com/alphagov/govuk-frontend-docs/issues/155

### Follow-up Work
- [x] Give the team a bit of breathing room between the release and the next epic we pick up - at least one week - to deal with extra support queries
- [ ] https://github.com/alphagov/govuk-design-system/issues/1884
