### ISSUE TITLE
Release GOV.UK Frontend v3.13.1

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2317]
## What
Do a patch release of fixes before we start work on v4.

## Who needs to know about this
Developers, Content Design, Tech Writer

## Done when

- [x] https://github.com/alphagov/govuk-frontend/issues/2319
- [x] https://github.com/alphagov/govuk-frontend/issues/2315
- [x] https://github.com/alphagov/govuk-prototype-kit/issues/1057
- [x] https://github.com/alphagov/govuk-frontend/issues/2318
- [x] https://github.com/alphagov/govuk-design-system/issues/1828
- [x] https://github.com/alphagov/govuk-prototype-kit/issues/1058
- [x] https://github.com/alphagov/govuk-prototype-kit/issues/1059
- [x] https://github.com/alphagov/govuk-design-system/pull/1856
