### ISSUE TITLE
Revisit our legacy browser support

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2503]
## What
We should revisit our level of support for older browsers (e.g: IE11). This work may help us inform some of the JavaScript work (https://github.com/alphagov/govuk-frontend/issues/1389), e.g:

- polyfills
- newer features we currently avoid to support older browsers
- tooling choices

## Why
It seems likely that the Service Manual may update the support for IE11 in the next year or so (e.g: removing or updating to 'functional' support). While we follow the Service Manual, we also know that roughly 40% of services that filled in the Government Frontend Survey 2021 still support IE11 (various reasons being: supporting staff/internal/legacy systems; high percentage of their users still use IE). At the moment, we support more browsers than those listed in the Service Manual, so we can set our level of support ourselves as long as we still meet the minimum required by the Service Manual.

## Who needs to work on this
Developers; Tech Writer

## Done when

- [x] https://github.com/alphagov/govuk-frontend/issues/2517
- [x] https://github.com/alphagov/govuk-frontend/issues/2519
- [ ] [parked] https://github.com/alphagov/govuk-frontend/issues/2518

**Comment by vanitabarrett** [comment]
Follow-up epic: https://github.com/alphagov/govuk-frontend/issues/2621
