### ISSUE TITLE
Release v4.1.0 of GOV.UK Frontend

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2598]
## What
Epic card for everything involved in the feature release v4.1.0

## Done when

- [x] Co-ordinate release with the GOV.UK Prototype Kit team if they are doing a corresponding release
- [x] Ensure all work in the [GOV.UK Frontend milestone](https://github.com/alphagov/govuk-frontend/milestone/44) and the [GOV.UK Design system milestone](https://github.com/alphagov/govuk-design-system/milestone/13) has been completed/is ready to go
- [x] https://github.com/alphagov/govuk-frontend/issues/2594
- [x] https://github.com/alphagov/govuk-frontend/issues/2595
- [x] https://github.com/alphagov/govuk-frontend/issues/2596
- [x] https://github.com/alphagov/govuk-design-system/issues/2147
- [x] alphagov/govuk-frontend-docs#184
- [x] https://github.com/alphagov/govuk-frontend/issues/2597

**Comment by domoscargin** [comment]
The Prototype Kit team aren't planning on doing a simultaneous release.
