### ISSUE TITLE
Reduce Internet Explorer (IE) support in GOV.UK Frontend

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2621]
## What

In our next major version (v5) we're reducing our support for Internet Explorer:

- dropping support completely for IE8 to 10
- dropping support for JavaScript in IE11 (while keeping support for styling)

### CSS 

We'll completely remove our support for IE8 to 10. Our components will keep rendering properly and remain functional in IE11 though.

### JavaScript

We will no longer support our component's JavaScript enhancement running in any version of Internet Explorer. People using IE11 will get the non-JavaScript version of the components, which will still let them complete their task.

We’ll continue to provide minimal support for v4 for the next 12 months by publishing urgent security updates and major bug fixes (but no new components or features).

## Why

We have decided to reduce support for IE11 in GOV.UK Frontend and drop support completely for IE8-10. We [shared these proposed changes](https://github.com/alphagov/govuk-frontend/discussions/2607) with the frontend community in GDS and across government, and have only received positive feedback.

We will make these changes in a future breaking release of GOV.UK Frontend (likely v5.0.0).
See our [browser proposal](https://github.com/alphagov/govuk-frontend/discussions/2607) for more details.

## Impact

Teams [still required to support IE11](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices#browsers-to-test-in-from-june-2022) will remain able to use our components. Those will be lacking their JavaScript enhancement but still allow users to complete their tasks as they are implemented with progressive enhancement in mind. 

During the 12 months after the release of v5, they'll also be able to keep using v4, for which JavaScript will keep running in Internet Explorer. 

## Epic lead

TBD

## Who needs to work on this

Developers, Designers, Tech writers

## Done when

```[tasklist]
### In v4.x
- [x] https://github.com/alphagov/govuk-frontend/issues/2625
- [x] https://github.com/alphagov/govuk-frontend/issues/2004
- [ ] #3163 
```

```[tasklist]
### Remove legacy code
- [ ] https://github.com/alphagov/govuk-frontend/issues/2622
- [ ] https://github.com/alphagov/govuk-frontend/issues/3461
- [ ] https://github.com/alphagov/govuk-frontend/issues/2506
- [ ] https://github.com/alphagov/govuk-frontend/issues/3464
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/188
- [ ] https://github.com/alphagov/govuk-frontend/issues/3624
```

```[tasklist]
### Post v5.0
- [ ] https://github.com/alphagov/govuk-frontend/issues/937
- [ ] https://github.com/alphagov/govuk-frontend/issues/3231
- [ ] https://github.com/alphagov/govuk-frontend/issues/3465
- [ ] https://github.com/alphagov/govuk-frontend/issues/3466
```

**Comment by vanitabarrett** [comment]
Written up a card for us to revisit our support of v4, 12 months after releasing this piece of work. https://github.com/alphagov/govuk-frontend/issues/2626

**Comment by colinrotherham** [comment]
Just moving some related comments from https://github.com/alphagov/govuk-frontend/pull/3559#issuecomment-1527577702 so we don't miss anything:

1. There's the SVG fallback `govuk-logotype-crown.png` image to delete:

   https://github.com/alphagov/govuk-frontend/blob/8ccbb6089bdfc957966274dfa4e2d2cadf73b2f2/src/govuk/components/header/template.njk#L38
   
   https://github.com/alphagov/govuk-frontend/blob/8ccbb6089bdfc957966274dfa4e2d2cadf73b2f2/src/govuk/components/header/_index.scss#L308

2. Documentation to test in Internet Explorer 8, 9 and 10

   https://github.com/alphagov/govuk-frontend/blob/8ccbb6089bdfc957966274dfa4e2d2cadf73b2f2/docs/contributing/testing.md#L61

   https://github.com/alphagov/govuk-frontend/blob/8ccbb6089bdfc957966274dfa4e2d2cadf73b2f2/CONTRIBUTING.md#L66

   https://github.com/alphagov/govuk-frontend/blob/8ccbb6089bdfc957966274dfa4e2d2cadf73b2f2/README.md#L42

   https://github.com/alphagov/govuk-frontend/blob/8ccbb6089bdfc957966274dfa4e2d2cadf73b2f2/README.md#L54

   https://github.com/alphagov/govuk-frontend/blob/8ccbb6089bdfc957966274dfa4e2d2cadf73b2f2/docs/contributing/coding-standards/css.md#L200

   https://github.com/alphagov/govuk-frontend/blob/8ccbb6089bdfc957966274dfa4e2d2cadf73b2f2/docs/contributing/resize-text-in-browsers.md#L46

**Comment by domoscargin** [comment]
Capturing some stuff we've been chatting about regarding non-vendor polyfills.

`[Intl.PluralRules](https://github.com/alphagov/govuk-frontend/blob/2c96f0e8d72f4d6332b0f9f75268920baa651488/packages/govuk-frontend/src/govuk/i18n.mjs#L115-L127)`

`[Intl.NumberFormat](https://github.com/alphagov/govuk-frontend/blob/2c96f0e8d72f4d6332b0f9f75268920baa651488/packages/govuk-frontend/src/govuk/i18n.mjs#L129-L141)`

`onpageshow` (in character-count, checkboxes, radios)

`HTMLDetailsElement` (in [Details](https://github.com/alphagov/govuk-frontend/issues/3464))

`matchMedia` (in header and tabs)

**Comment by domoscargin** [comment]
Some non-obvious IE-related things to remove:

* https://github.com/alphagov/govuk-frontend/blob/2c96f0e8d72f4d6332b0f9f75268920baa651488/packages/govuk-frontend/src/govuk/template.njk#L11-L12
* https://github.com/alphagov/govuk-frontend/blob/2c96f0e8d72f4d6332b0f9f75268920baa651488/packages/govuk-frontend/src/govuk/components/components.template.test.js#L61-L63

**Comment by domoscargin** [comment]
> Some non-obvious IE-related things to remove:
> 
> * https://github.com/alphagov/govuk-frontend/blob/2c96f0e8d72f4d6332b0f9f75268920baa651488/packages/govuk-frontend/src/govuk/template.njk#L11-L12
> * https://github.com/alphagov/govuk-frontend/blob/2c96f0e8d72f4d6332b0f9f75268920baa651488/packages/govuk-frontend/src/govuk/components/components.template.test.js#L61-L63
> * `focusable="false"` on SVGs https://github.com/alphagov/govuk-frontend/blob/2c96f0e8d72f4d6332b0f9f75268920baa651488/packages/govuk-frontend/src/govuk/components/button/template.njk#L21-L23

@querkmachine I have no memory of writing this post, but are these worth cleaning up? Looks like the first two only apply to older IE which we shouldn't need any more. The last one might still be in IE11 and thus in that iffy zone.

**Comment by querkmachine** [comment]
@domoscargin They're dealt with!

- https://github.com/alphagov/govuk-frontend/pull/4434
- https://github.com/alphagov/govuk-frontend/pull/4854

And yeah, `focusable="false"` is still necessary for IE11 for the time being.

**Comment by domoscargin** [comment]
Whoops, I was looking at that commit rather than `main`. Call it a case of the Mondays.

Nice!
