### ISSUE TITLE
Release GOV.UK Frontend 4.2.0

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#2665]
## What
Epic card for everything involved in the fix release v4.2.0

## Why
We want to release the pagination component and some fixes.

## Dependencies
When the cards in the milestone are completed: https://github.com/alphagov/govuk-frontend/milestone/47

## Done when

- [x] https://github.com/alphagov/govuk-frontend/issues/2661
- [x] https://github.com/alphagov/govuk-frontend/issues/2662
- [x] https://github.com/alphagov/govuk-frontend/issues/2663
- [x] https://github.com/alphagov/govuk-design-system/issues/2222
- [x] https://github.com/alphagov/govuk-frontend-docs/issues/198
- [x] https://github.com/alphagov/govuk-frontend/issues/2664
