### ISSUE TITLE
Release GOV.UK Frontend 4.3.0

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-frontend#2728]
## What
Do a feature release of GOV.UK Frontend.

## Why
We have a lot of fixes we want to release, including one which adds to the template API.

## Who needs to work on this
Developers; Tech writer; Content designer

## Done when
- [x] Ensure all work in the [GOV.UK Frontend milestone](https://github.com/alphagov/govuk-frontend/milestone/48) and the [GOV.UK Design system milestone](https://github.com/alphagov/govuk-design-system/milestone/14) has been completed/is ready to go
- [x] https://github.com/alphagov/govuk-frontend/issues/2729
- [x] https://github.com/alphagov/govuk-frontend/issues/2730
- [x] https://github.com/alphagov/govuk-frontend/issues/2731
- [x] https://github.com/alphagov/govuk-design-system/issues/2271
- [x] Merge all PRs in the [GOV.UK Design system milestone](https://github.com/alphagov/govuk-design-system/milestone/14)
- [x] https://github.com/alphagov/govuk-frontend-docs/issues/201
- [x] https://github.com/alphagov/govuk-frontend/issues/2732
