### ISSUE TITLE
Remove compatibility mode

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-frontend#2769]
## What we'll do

We'll remove [compatibility mode](https://frontend.design-system.service.gov.uk/compatibility-mode/) from GOV.UK Frontend.

Compatibility mode exists to make it easier for users to [migrate from our old frameworks](https://frontend.design-system.service.gov.uk/migrating-from-legacy-products/#migrate-from-our-old-frameworks) (GOV.UK Elements, GOV.UK Frontend Toolkit and GOV.UK Template).

When compatibility mode is enabled, GOV.UK Frontend:

- uses the old colour palette
- uses the old GOV.UK font from GOV.UK Template
- overrides some of the CSS in the legacy frameworks
- no longer uses rem for font sizes

## Why we're doing it

We're [making changes to the typography scale](https://github.com/alphagov/govuk-design-system/issues/2289) used in GOV.UK Frontend.

Without significant effort from us (to support two different typography scales), users who have enabled compatibility mode would see a mix of different sized text in their services.

Given that the Design System is now a live service and it's been nearly 5 years since the last release of GOV.UK Elements, we think it's now time to retire compatibility mode.

## How this impacts our users

Teams that are still using our old frameworks will not be able to migrate directly to v5.0 or above. However, they will still  have a migration path – they'll just need to finish migrating to the latest version of GOV.UK Frontend v4 (which will still support compatibility mode) and then upgrade to v5 in a separate step.

## Epic lead
Owen

## Who needs to work on this
Developers

## Done when

In v4.x we will:

```[tasklist]
- [x] Investigate where compatibility mode is being used in govuk-frontend
- [x] Assess if there are any functions that compatibility mode facilitates that we want to keep
- [x] https://github.com/alphagov/govuk-frontend/issues/2787
- [x] https://github.com/alphagov/govuk-frontend/issues/2890
- [x] https://github.com/alphagov/govuk-frontend/issues/2788
- [ ] https://github.com/alphagov/govuk-frontend/issues/2789
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/207
```

In v5.0 we will:

```[tasklist]
- [ ] https://github.com/alphagov/govuk-frontend/issues/2790
- [ ] https://github.com/alphagov/govuk-frontend/issues/2791
- [ ] https://github.com/alphagov/govuk-frontend/issues/2792
- [ ] https://github.com/alphagov/govuk-frontend/issues/2793
- [ ] https://github.com/alphagov/govuk-frontend/issues/2794
- [ ] https://github.com/alphagov/govuk-frontend/issues/2795
- [ ] https://github.com/alphagov/govuk-frontend/issues/3583
```

**Comment by owenatgov** [comment]
# Where we use compatibility
The compatibility variables, excluding tests, are referenced in the following places:

- https://github.com/alphagov/govuk-frontend/blob/main/app/assets/scss/app-legacy-ie8.scss
- https://github.com/alphagov/govuk-frontend/blob/main/app/assets/scss/app-legacy.scss
- https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/settings/_compatibility.scss
- https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/settings/_colours-palette.scss
- https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/settings/_typography-font.scss
- https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/settings/_typography-responsive.scss

The first 2 we can ignore and remove once this work is ready to go out with 5.0 as they are examples of compatibility mode in use in our own review app.

The rest however are specifying settings for the rest of the codebase. The compatibility setting is a private array which is used in the [govuk-compatibility](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/tools/_compatibility.scss) mixin and the rest set the following global variables:

- `$govuk-use-legacy-palette`
- `$govuk-use-legacy-font`
- `$govuk-typography-use-rem`

All 4 of these impact various components, styles and helpers. See the below table for which components/styles/helpers are impacted and how each of these use the compatibility settings:

| Component/Style/Helper | `govuk-compatibility` | `$govuk-use-legacy-palette` | `$govuk-use-legacy-font` | `$govuk-typography-use-rem` |
| -- | -- | -- | -- | -- |
| [Back link](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/back-link/_index.scss) | | | ✅ | |
| [Breadcrumbs](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/breadcrumbs/_index.scss) | | | ✅ | |
| [Button](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/button/_index.scss) | ✅ | | ✅ | |
| [Footer](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/footer/_index.scss) | ✅ | ✅ | | |
| [Header](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/header/_index.scss) | | | ✅ | |
| [Input](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/input/_index.scss) | | | | ✅ |
| [Table](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/table/_index.scss) | ✅ | | | |
| [Tag](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/tag/_index.scss) | | | ✅ | |
| [Select](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/select/_index.scss) | | | | ✅ |
| [Section break](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/core/_section-break.scss) | ✅ | | | |
| [Colour](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/helpers/_colour.scss) | | ✅ | | |
| [Links](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/helpers/_links.scss) | ✅ | | | |
| [Typography](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/helpers/_typography.scss) | | | | ✅ |

Before we proceed with deprecation, we should decide if any of these settings currently managed via compatibility mode vars are worth keeping and then expose them more explicitly for use by teams. My personal view is that as most of these pertain to legacy instances of govuk-frontend, they should simply be deprecated and removed. The sole exception is `$govuk-typography-use-rem` however I'm skeptical about how useful this is and if we should be shipping it as an option outside the scope of compatibility mode. I will confer with the team before proceeding.

**Comment by owenatgov** [comment]
Thanks for the high quality sleuthing @36degrees. I've shuffled both these into the removal of `$govuk-use-legacy-font` (proper issue incoming) as they're both informed by that setting.

**Comment by owenatgov** [comment]
@36degrees recently raised a valid point about if this would create noise from deprecation warnings for users who are staying on v4. We've decided that we're going to keep an eye on this after we release v5 and update v4 to remove the warnings if users still on v4 complain about this.
