### ISSUE TITLE
Release GOV.UK Frontend 4.4.0

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#2958]
## What
Do a feature release of GOV.UK Frontend.

## Why
We have a lot of fixes we want to release, including the addition of localisation.

## Who needs to work on this
Developers; Tech writer; Content designer

## Done when
- [x] Ensure all work in the [GOV.UK Frontend milestone](https://github.com/alphagov/govuk-frontend/milestone/50) and the [GOV.UK Design system milestone](https://github.com/alphagov/govuk-design-system/milestone/15) has been completed/is ready to go
- [x] https://github.com/alphagov/govuk-frontend/issues/2954
- [x] https://github.com/alphagov/govuk-frontend/issues/2955
- [x] https://github.com/alphagov/govuk-frontend/issues/2956
- [x] https://github.com/alphagov/govuk-design-system/issues/2409
- [x] https://github.com/alphagov/govuk-frontend-docs/issues/218

**Comment by colinrotherham** [comment]
Will close this one, but still got "comms" unticked (just Twitter left?) on:

* https://github.com/alphagov/govuk-frontend/issues/2957
