### ISSUE TITLE
Audit and update "JavaScript work" epic

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#2961]
## What
Review our [JavaScript epic](https://github.com/alphagov/govuk-frontend/issues/1389) and ensure it's up to date, with all relevant tickets attached to it, or its child epics.

Related: https://docs.google.com/presentation/d/1FPaDB0brW_qTqD8TQQPjX6pQx1gDAm-2SAc4Vs52Mn8/edit#slide=id.gf5f38cbc77_0_113

## Why
It's been a hot minute since we reviewed our [JavaScript epic](https://github.com/alphagov/govuk-frontend/issues/1389), and with new members joining the team it'd be good to get a grip on the overarching goals of the work and arrange the team's collective mind palace so we can prioritise work, plan a release schedule and break down the tasks.

## Who needs to work on this
Developer

## Who needs to review this
Tech Lead

## Done when

- [x] [JavaScript epic](https://github.com/alphagov/govuk-frontend/issues/1389) is up to date (including work completed). It doesn't have to be 100% accurate to our upcoming plans.
- [x] All related tasks added to the architectural changes board: https://github.com/orgs/alphagov/projects/41
- [x] Issues and PR "sweep" to pick up any related work
