### ISSUE TITLE
Update styles, components and patterns to WCAG 2.2 AA

### ISSUE THREAD

**Issue by davidc-gds** [alphagov/govuk-frontend#3040]
## What

**Timeline:** November 2022 to June 2023
**Priority level:** 1 – what we must do legally

## Potential tasks

- Assess the readiness and work needed to bring the GOV.UK Design System in line with WCAG 2.2
- Determine which styles, components and patterns require updating or further research
- Update styles, components and patterns, likely with a ‘breaking release’

## Why

WCAG 2.2 is set to be published in 2023. 

We plan to release a version of the GOV.UK Frontend library that has styles, components and patterns which meet WCAG 2.2. Our goal is to release that around 6 months after WCAG 2.2 is officially published.

We're hoping that releasing at the 6-month mark still gives service teams enough time to implement the updated GOV.UK Frontend version into their services, before the not-yet-confirmed grace period expires.

## Who needs to work on this
Everyone: developers, interaction designers, user researcher, accessibility specialist, content designers, product manager.

## Who needs to review this
Inside the team: tech leads and accessibility specialist.

Outside the team: ideally service teams in the design system community.

## Done when
- [ ] Assess the readiness and work needed to bring the GOV.UK Design System in line with WCAG 2.2
- [ ] Determine which styles, components and patterns require updating or further research
- [ ] Update styles, components and patterns, likely with a ‘breaking release’
