### ISSUE TITLE
Release GOV.UK Frontend 4.5.0

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-frontend#3171]
## What
Do a feature release of GOV.UK Frontend from 4.4.1.

## Why
We've got several new features we want to ship.

## Who needs to work on this
Developers, Tech writers, Content designers

## Done when

- [x] https://github.com/alphagov/govuk-frontend/issues/3172
- [x] https://github.com/alphagov/govuk-frontend/issues/3173
- [x] https://github.com/alphagov/govuk-frontend/issues/3174
- [x] https://github.com/alphagov/govuk-design-system/issues/2534
- [x] https://github.com/alphagov/govuk-frontend-docs/issues/289
- [x] https://github.com/alphagov/govuk-frontend/issues/3175
