### ISSUE TITLE
Expand the browsers we automatically test in

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3278]
> **Note** This piece of work should only start after we've released v5

## What

Increase the browsers we run our automated tests in, using a more modern testing tool (either [Playwright](https://playwright.dev/) or [webdriver.io](https://webdriver.io/). 

## Why

Our automated tests (powered by [Puppeteer](https://pptr.dev/)) only run against Chrome, leaving many browsers to manual testing. Newer tools allow to test in a wider range of browsers, which would save us some time and give us more confidence. Especially:
- with more complex components coming up, like a new autocomplete, requiring more interactions to test
- with our changes in browser support, where we may want to test the first versions we support

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] [Spike a comparison of the tools](https://github.com/alphagov/govuk-frontend/issues/3049) – [Comparison results](https://docs.google.com/presentation/d/140GMIjM9PKOGq3zHRK2h2lByQdbcFwFhkIjX2qnbtt0/edit?usp=sharing)
- [ ] Investigate possible costs to using SauceLabs
- [ ] Plan how we'd migrate our codebase from Puppeteer to one of these tools, either in one go, but ideally in smaller steps[^1]

[^1] One example could be having a custom jest environment allowing us to run, say, webdriver for some tests and keep puppeteer for others while we migrate.

**Comment by stevenjmesser** [comment]
I've added this to sprint 6 so that we can review whether we want to start it then. We might push it into Q1 23/24 which is fine. We don't have to start it in sprint 6, it just serves as a reminder to review the card.

**Comment by christian-bromann** [comment]
> 1. One example could be having a custom jest environment allowing us to run, say, webdriver for some tests and keep puppeteer for others while we migrate. [↩](#user-content-fnref-1-2f1975e028b2e8cd2a4da2a5bedbcaff)

With WebdriverIO you can use both the WebDriver protocol and Puppeteer.

**Comment by colinrotherham** [comment]
Just a little update on this

It's looking like Internet Explorer 11 works now in [**WebdriverIO** v8](https://webdriver.io/blog/2022/12/01/webdriverio-v8-released/) with some recent patches in [#11705](https://github.com/webdriverio/webdriverio/issues/11705), [#11711](https://github.com/webdriverio/webdriverio/issues/11711) and [#11716](https://github.com/webdriverio/webdriverio/issues/11716). We're very aware too that our [**Puppeteer** tests are limited to Chrome](https://pptr.dev/faq#q-what-is-the-status-of-cross-browser-support) and [**JSDOM** lacks ES module support](https://github.com/jsdom/jsdom/blob/a39e0ec4ce9a8806692d986a7ed0cd565ec7498a/lib/jsdom/living/nodes/HTMLScriptElement-impl.js#L160-L162)

With our [Browser grades](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/browser-support.md#browsers-grades) in mind, we should note some automation gaps:

* Grade C browser tests to confirm Babel transforms and polyfills work
* Grade X browser tests (e.g. Internet Explorer 11) to confirm the "no-JS" experience

WebdriverIO seems perfect for this

Recently our [Puppeteer tests moved to `*.puppeteer.test.js`](https://github.com/alphagov/govuk-frontend/pull/4205) so could we do the same for WebdriverIO?
