### ISSUE TITLE
Track performance impacts of built files

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3279]
## What

Monitor metrics to judge how our built files may affect performance of projects using `govuk-frontend`. This includes the files in `dist` as well as those inside `package`.

This should be as automated as we can to save us the time of gathering and comparing these metrics, but could be implemented progressively. 

## Why

While we do a `diff` of the files in `dist` before releasing, it'd be good to keep an eye on the size and contents of both `dist` and `package`, so we can spot  unexpected variations closer to when we make the changes. 

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Tasks

> **Note** Issues for each of those coming soon

- [ ] Gather built file sizes and display them
- [ ] Gather breakdown of module contents
- [ ] Display performance metrics on PRs
- [ ] Keep tracking impact of polyfills once automated
- [ ] Compare file sizes between branches
- [ ] Compare breakdowns of modules between branches
- [ ] Break build when impact is too big
- [ ] Measure impact of transpiling
- [ ] Investigate having only one build
- [ ] Investigate not having `dist` and `package` in the repository

**Comment by stevenjmesser** [comment]
Moving this epic to the backlog so the individual tasks can come through the board.

**Comment by colinrotherham** [comment]
Going to move this back to the Backlog for post v5 tasks
