### ISSUE TITLE
Keep tracking impact of polyfills once automated

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3283]
Part of #3279 

> **Note** This only applies if we start using Babel to automatically add polyfills to our components

## What

Track which polyfills our modules need and how weighty they are after Babel adds them to our code when bundling our components.

## Why

Currently, our polyfills are vendored in the package we ship. This means we're able to track their impact when looking at what's brought in when importing our modules. If we move to Babel to automatically import polyfills, we'll need to make sure we still keep track of the impact of our polyfills.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] We figured a way to collect polyfill impact[^1]
- [ ] We display impact in review app
- [ ] We display impact in a PR comment
