### ISSUE TITLE
Enhance the structure of our repository

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3291]
## What

We're reorganising the files in our repository to have a better to work with. See the issues for details about each move and its reason.

## Why

A better structure for our repository allows us to:
- acknowledge its [monorepo](https://en.wikipedia.org/wiki/Monorepo) nature (having both our library and the review app, alongside various helpers), 
- provide better isolation between the different parts of the project
- avoid future breaking changes should we need dependencies 
- limit our use of relative paths when importing from each part of the project.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

```[tasklist]
### v5
- [ ] https://github.com/alphagov/govuk-frontend/issues/2886
- [ ] https://github.com/alphagov/govuk-frontend/issues/3547
- [ ] https://github.com/alphagov/govuk-frontend/issues/3548
- [ ] https://github.com/alphagov/govuk-frontend/issues/3639
```

```[tasklist]
### Future changes
- [ ] Investigate [replacing Jest wildcards with per workspace configs](https://github.com/alphagov/govuk-frontend/issues/2886#issuecomment-1261027939)
- [x] Investigate consolidating build to a single command
- [x] https://github.com/alphagov/govuk-frontend/pull/3498
- [ ] https://github.com/alphagov/govuk-frontend/pull/3490
```

**Comment by colinrotherham** [comment]
Versioning **./package** seems to let other projects clone the repo (or use git submodules) to pull `govuk-frontend` yet have all the files, pre-built, ready to go without needing an `npm install` or extra build steps?

* https://github.com/alphagov/govuk-frontend/pull/732
* https://github.com/alphagov/govuk-frontend/pull/1458

Can see a bit of history in older releases:

* https://github.com/alphagov/govuk-frontend/pull/791

```html
<script src="{path-to-govuk-frontend}/all.js"></script>
<script>window.GOVUKFrontend.initAll()</script>
```

☝️ This release has details about the old namespaced package `@govuk-frontend/frontend`

**Comment by romaricpascal** [comment]
Didn't think of cloning/submodules to access the source (and cheers for the issue archeology 😄). 

That said, cloning `govuk-frontend` (or using it as submodule) to access `package` may not give you what you expect. If you clone `main` at the moment, you'll get the package from the last release, not the package corresponding to the source in `main`.

**Comment by romaricpascal** [comment]
Linking https://github.com/alphagov/govuk-frontend/issues/2886 to keep track of the related ongoing discussions around the reorganisation of ther repo :)
