### ISSUE TITLE
Release GOV.UK Frontend v4.6.0

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-frontend#3320]
## What

Release a new version of GOV.UK Frontend. This is likely to be the last version of GOV.UK Frontend before we start working on v5.0.

## Why

So that users who aren't able to upgrade to v5 are using a version of v4 that's free of a few easily fixable bugs.

## Who needs to work on this

Developers, Tech writers, Content designers

## Done when

```[tasklist]
- [ ] https://github.com/alphagov/govuk-frontend/issues/3474
- [ ] https://github.com/alphagov/govuk-frontend/issues/3475
- [ ] https://github.com/alphagov/govuk-frontend/issues/3476
- [ ] https://github.com/alphagov/govuk-design-system/issues/2717
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/304
- [ ] https://github.com/alphagov/govuk-frontend/issues/3480
```
