### ISSUE TITLE
Clarify our JavaScript components' public API

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3478]
## What

We're drawing a clear line between the properties and methods of our JavaScript components that are meant to be publicly accessed and those that are only for internal use.

## Why

Currently, there's no clear distinction about what's for internal us and what's meant to be used by service code. This makes a very wide area for breaking changes, that we don't intentionally control, slowing down our capacity to make changes in places that should be private but are exposed. Also, while accessible to service code, some of these properties and methods are also not designed for outside use in their API.

With the opportunity for breaking changes in v5, this is a chance to clearly separate public and private APIs. This provides to services clarity on what our components are designed to offer, and to us safety when deciding what we can change without it being a breaking change.

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

## Done when

```[tasklist]
### v4
- [ ] https://github.com/alphagov/govuk-frontend/issues/3473
```

```[tasklist]
### v5
- [ ] https://github.com/alphagov/govuk-frontend/issues/3479
- [ ] https://github.com/alphagov/govuk-frontend/issues/4008
- [ ] https://github.com/alphagov/govuk-frontend/issues/4009
- [ ] https://github.com/alphagov/govuk-frontend/issues/4035
- [ ] https://github.com/alphagov/govuk-frontend/issues/4128
- [ ] https://github.com/alphagov/govuk-frontend/issues/4129
- [ ] https://github.com/alphagov/govuk-frontend/issues/4130
- [ ] https://github.com/alphagov/govuk-frontend/issues/4131
- [ ] https://github.com/alphagov/govuk-frontend/issues/4125
- [ ] https://github.com/alphagov/govuk-frontend/issues/4126
- [ ] https://github.com/alphagov/govuk-frontend/issues/4127
- [ ] https://github.com/alphagov/govuk-frontend/issues/4144
- [ ] https://github.com/alphagov/govuk-frontend/issues/4036
- [ ] https://github.com/alphagov/govuk-frontend/issues/4037
- [ ] https://github.com/alphagov/govuk-frontend/issues/4074
- [ ] https://github.com/alphagov/govuk-frontend/issues/4073
- [ ] https://github.com/alphagov/govuk-frontend/issues/4010
- [ ] https://github.com/alphagov/govuk-frontend/issues/3904
- [ ] https://github.com/alphagov/govuk-frontend/issues/4017
- [ ] https://github.com/alphagov/govuk-frontend/issues/4072
- [ ] https://github.com/alphagov/govuk-frontend/issues/4076
- [ ] https://github.com/alphagov/govuk-frontend/issues/4103
- [ ] https://github.com/alphagov/govuk-frontend/issues/4209
- [ ] https://github.com/alphagov/govuk-frontend/issues/4299
- [ ] https://github.com/alphagov/govuk-frontend/issues/4300
```
```[tasklist]
### Post v5
- [ ] https://github.com/alphagov/govuk-frontend/issues/4071
```

**Comment by 36degrees** [comment]
All the tasks in the list are done, so I'm gonna say we can close this! 🎉
