### ISSUE TITLE
Prepare support for parallel documentation of v4 and v5

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3483]
## What

Plan how we'll provide documentation for both v4 and v5 at the same time during the period we'll be supporting both versions and implement it for both the Design System and Frontend Docs websites. We'll especially need to think that part of the Design System that we update post v5 (eg. guidance on patterns) may still be relevant for people using v4.

## Why

We're commiting to support v4 for a time after launching v5. We'll need people to access both documentations during that period, so they can still find information about v4.

## Who needs to work on this

Developers, Designers, Tech writers

## Who needs to review this

Developers, Designers, Tech writers

## Done when

```[tasklist]
1. [ ] https://github.com/alphagov/govuk-frontend/issues/3549
2. [ ] https://github.com/alphagov/govuk-design-system/issues/2186
3. [ ] https://github.com/alphagov/govuk-frontend-docs/issues/189
1. [ ] https://github.com/alphagov/govuk-frontend-docs/issues/189
```

**Comment by claireashworth** [comment]
Closing this issue to remove some duplication and making #2186 the epic instead.
