### ISSUE TITLE
Implement newer techniques made available by our support strategy

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3505]
## What

We're updating our components to use actual [classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) rather than functions with a prototype.

Internally, we're also updating our tools now they're no longer held back by the need to support old browsers.

## Why

Besides their more compact syntax, using classes will open the door to factorising common component behaviours so it can be inherited by the different components sharing them.

Updating our tools will allow us to benefit from their latest features.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Tasks

```[tasklist]
### Done when
1. [ ] https://github.com/alphagov/govuk-frontend/issues/3462
1. [ ] https://github.com/alphagov/govuk-frontend/issues/3463
5. [ ] Migrate JavaScript to ES6 classes
```
