### ISSUE TITLE
Improve diffing of `dist`

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3544]
## What

We're looking to improve how we run the diffs of `dist` ran ahead of releases to:

- refactor some code so we can comment on PRs not only at release time but for other purposes
- work around the Github's limit of 65536 characters for comments

## Why

We're looking to expand when we post comments on our PRs. This calls for a reusable way of commenting that's capable of editing the same comment as new commits are made.

We've also bumped into Github's limit when commenting the `diff` of the last couple of releases. That's something we need to work around to facilitate the reviews of the future releases.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

```[tasklist]
- [ ] https://github.com/alphagov/govuk-frontend/issues/3545
- [ ] https://github.com/alphagov/govuk-frontend/issues/3546
- [ ] https://github.com/alphagov/govuk-frontend/issues/3229
```
