### ISSUE TITLE
Pre-release v5

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-frontend#3640]
## What

Provide pre-release(s?) of v5 before shipping the actual release. We need first to discuss:
- at which point it'd be relevant to pre-release 
- in which way (actual npm pre-release or Github ones) 

## Why

v5 brings substantial changes to what we'll be shipping. Providing pre-releases will let people test early and give us feedback on anything that may need tweaking before the final release.

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

## Done when

```[tasklist]
### Done when
- [ ] https://github.com/alphagov/govuk-frontend/issues/4029
- [ ] https://github.com/alphagov/govuk-frontend/issues/4228
- [ ] https://github.com/alphagov/govuk-frontend/issues/4229
- [ ] https://github.com/alphagov/govuk-frontend/issues/4292
- [ ] https://github.com/alphagov/govuk-frontend/issues/4293
- [ ] https://github.com/alphagov/govuk-frontend/issues/4294
- [ ] https://github.com/alphagov/govuk-frontend/issues/4295
- [ ] https://github.com/alphagov/govuk-frontend/issues/4396
- [ ] https://github.com/alphagov/govuk-frontend/issues/3661
- [ ] https://github.com/alphagov/govuk-frontend/issues/4418
- [ ] https://github.com/alphagov/govuk-frontend/issues/4475
```

```[tasklist]
### Pre-release feedback
- [ ] https://github.com/alphagov/govuk-frontend/pull/4391
- [ ] https://github.com/alphagov/govuk-frontend/pull/4392
- [ ] https://github.com/alphagov/govuk-frontend/pull/4394
- [ ] https://github.com/alphagov/govuk-frontend/issues/4436
- [ ] https://github.com/alphagov/govuk-frontend/issues/4437
- [ ] https://github.com/alphagov/govuk-frontend/issues/4474
- [ ] https://github.com/alphagov/govuk-frontend/issues/4476
- [ ] https://github.com/alphagov/govuk-frontend/issues/4477
```

**Comment by romaricpascal** [comment]
A couple of options:
- Could we automatically [build a pre-release branch](https://github.com/alphagov/govuk-frontend/blob/main/bin/pre-release.sh#L4) for `main` after each merge (via a Github action)?
- Colin floated the possibility of pre-releasing PRs to Github's [npm registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry) automatically so that each PR can be tested that way. This could include Github actions running against that published version (for testing for ex.).
- And there's of course the option to [manually publish a pre-release package to `npm`](https://github.com/alphagov/govuk-frontend/blob/main/docs/releasing/publishing-a-pre-release.md)

**Comment by colinrotherham** [comment]
When manually publishing a pre-release we'd typically publish to a GitHub branch

But we should consider `npm publish --tag next` for access to our "next" release alongside "latest":

```console
npm install govuk-frontend@latest
npm install govuk-frontend@next
```

Along with the tag ~`@latest`~ `@next` we can use a “release candidate” version number:

### Bump v4.7.0 to v5.0.0-rc.0

```console
npm version premajor --preid rc --no-git-tag-version --workspace govuk-frontend
```

### Bump v5.0.0-rc.0 to v5.0.0-rc.1

```console
npm version prerelease --preid rc --no-git-tag-version --workspace govuk-frontend
```
