### ISSUE TITLE
Define which methods for loading govuk-frontend we want to support in v5.0

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-frontend#3721]
## What

List the methods we want to offer users for loading GOV.UK Frontend in their project, based on: 

- the impact on users that are currently loading GOV.UK Frontend in one of the various ways they may do it with v4 and their "market size"
- whether dropping one of the approaches would paint it in the corner (eg. have to make a new major release) should it be missing in v5.0
- the effort it would take to keep providing each approach in v5.0 

For reference, with v4, people may be loading our package through:

- [`window.GOVUKFrontend` global](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#add-the-javascript-file-to-your-html)
- AMD (via UMD)
- CommonJS (via UMD)
- ES modules
	- Potentially following [package exports](https://nodejs.org/docs/latest-v14.x/api/packages.html#packages_exports) 

## Why

With v4, users can load `govuk-frontend` in their projects in a variety of ways. We'll need to decide which ways should be available in v5, to be able to document breaking changes and inform the content of our package and tooling (bundling, especially) needs.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

```[tasklist]
### Tasks
- [x] Create an inventory of the JavaScript loading methods we currently support
- [ ] Do some scrappy market-sizing (not thorough) for each of those approaches, and work out what we might need to do to continue supporting those (effort)
- [ ] Share a doc with the team to collect thoughts asyncrhonously, so that we don't paint ourselves in to a corner
- [ ] Decide in a workshop which of these we need to continue supporting, or might paint ourselves into a corner by not supporting (if a clear decision isn't present in the comments on a doc)
```

**Comment by colinrotherham** [comment]
Adding an example for Node.js [`require.resolve()`](https://nodejs.org/api/modules.html#requireresolverequest-options) to locate our assets directory for Express.js

```cjs
const { dirname, join } = require('path')

// `govuk-frontend@4` /path/to/project/node_modules/govuk-frontend/govuk/assets
// `govuk-frontend@5` /path/to/project/node_modules/govuk-frontend/dist/govuk/assets

const assetsPath = join(dirname(require.resolve('govuk-frontend')), 'assets')
```

Where `require.resolve()` resolves from **package.json** CommonJS exports like:

```json
"require": "./govuk/all.js"
```

So upcoming changes like the move to ~`govuk`~ → **`dist/govuk`** follows the export automatically

Versus [joining paths](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#serve-the-assets-from-the-gov-uk-frontend-assets-folder-recommended) which we've recommended previously

**Comment by romaricpascal** [comment]
Gathered information spread across the table, this issue, some discussion and [Colin's spike](https://github.com/alphagov/govuk-frontend/pull/3726) in [this (internal) document](https://docs.google.com/document/d/1mcLBDR-LO5khDmGhpDk-qhiRuF-RiEVWWPOGa2WtsJ4/edit#) for comment.

**Comment by 36degrees** [comment]
We've done this and we're writing up the decisions we made as part of #3482.
