### ISSUE TITLE
Ensure consistency between v5.0 and any v4.x support releases

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#3775]
## What

Ensure that changes released from the `v4.x` support branch have also been applied to the `main` branch ready for the v5.0 release.

Ensure that the changelog makes sense from a user's perspective, so anything 'already released' in v4 are not duplicated and any support releases are included in the changelog file.

## Why

We're intending to release at least 1 further version of GOV.UK Frontend v4 from a support branch whilst we continue to work on v5 on the `main` branch.

Any changes made on the support branch will also need to be applied to the `main` branch to avoid regressions.

## Who needs to work on this

Developers, tech writer

## Who needs to review this

Developers, tech writer

## Done when

```[tasklist]
### Tasks
- [ ] Any changes made in the v4.x support branch have also been applied to the branch for v5
- [ ] Any changes released from the v4.x support branch before the release of v5 have been removed from the changelog
- [ ] The release notes for v4.x support releases have been added to the changelog
```

**Comment by owenatgov** [comment]
We've ported everything forward from 4.7, however we'll keep this ope until 5.0 is released to make sure we check before publishing and in case we want to backport any improvements in 5.0 to 4.x.

**Comment by romaricpascal** [comment]
Judging by [the diff of what was added on support/4.x since 4.7.0](https://github.com/alphagov/govuk-frontend/compare/8a0f9eda1316e82d130966015721b237c78ce9ad...support/4.x#diff-4c04a4bdc47c9baf9288185466278d105450f45ab1b86f81e72696910572f4a8), we have nothing to port to the `main` branch 🥳
