### ISSUE TITLE
Create and publish documentation for DAC Audit 2023

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-frontend#3814]
## What

This ticket completes work related to the DAC audit 2023 and how we share results of the audit more publicly.   

## Why

This WCAG 2.2 audit supports our efforts to https://github.com/alphagov/govuk-frontend/issues/3040.

As we approach [the publishing date for WCAG 2.2](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/), we want to ensure our existing govuk-frontend elements are meeting all WCAG 2.1 AA criteria. The only way to pass WCAG 2.2 AA is to also meet all criteria in WCAG 2.1 AA ([with one exception, where a criterion is being removed](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/#changes-from-wcag-21-to-wcag-22)).
We're doing other work to assess where updates are needed to align elements with the 9 new WCAG 2.2 criteria, but we likely don't have capacity to run an internal audit across all of the existing 78 WCAG criteria.

## Who needs to work on this
@CharlotteDowns, @davidc-gds

## Who needs to review this
@stevenjmesser

## Done when
- [x] Check the usability results against our teams collective understanding
- [x] Consider writing a blog post, look to see if an accessibility audit is a new topic
- [x] Determine work needed to publish DAC audit reports on the Design System website (we can publish but waiting on other epics to determine where)
- [x] Receive approval from DAC to share publicly
- [x] Decide what items to add to the accessibility statement
- [x] Determine where remaining guidance changes are monitored (**at the moment they have been monitored here as a comment but will think about how that can be improved**)
```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-design-system/pull/2995
- [ ] https://github.com/alphagov/govuk-design-system/pull/2996
```

**Comment by CharlotteDowns** [comment]
Blog posts that relate to an accessibility audit:

- [Bringing accessibility audits in-house](https://accessibility.blog.gov.uk/2020/12/01/bringing-accessibility-audits-in-house/)
- [How we made GOV.UK more accessible](https://accessibility.blog.gov.uk/2020/12/17/how-we-made-gov-uk-more-accessible/)

**Comment by CharlotteDowns** [comment]
## Components and patterns that need a guidance change

### WCAG criteria
- [ ] Step-by-step navigation, [#2794](https://github.com/alphagov/govuk-design-system/issues/2794) and usability criteria [#3687](https://github.com/alphagov/govuk-frontend/issues/3687)
- [ ] Password (show/hide), [#2795](https://github.com/alphagov/govuk-design-system/issues/2795)
- [ ] Tabs, [#2797](https://github.com/alphagov/govuk-design-system/issues/2797)
- [ ] Links, [#2796](https://github.com/alphagov/govuk-design-system/issues/2796)
### Usability criteria
- [ ] Error message, Error summary, [#2801](https://github.com/alphagov/govuk-design-system/issues/2801)
- [ ] Pagination, [#3682](https://github.com/alphagov/govuk-frontend/issues/3682)
- [ ] Character count, [#3689](https://github.com/alphagov/govuk-frontend/issues/3689)

## Components and patterns that need a comment added to our accessibility statement

- [ ] Summary list, [#3673](https://github.com/alphagov/govuk-frontend/issues/3673) and [#3674](https://github.com/alphagov/govuk-frontend/issues/3674)
- [ ] Details, [#3693](https://github.com/alphagov/govuk-frontend/issues/3693)
- [ ] File upload, [#3685](https://github.com/alphagov/govuk-frontend/issues/3685) and [#3686](https://github.com/alphagov/govuk-frontend/issues/3686)

**Comment by CharlotteDowns** [comment]
## Accessibility statement changes

Drafted in [July 2023 accessibility statement update google document](https://docs.google.com/document/d/1Isr0WwmCZayCs9sTgyizzsJVKF0rRL_UUVo8lQrtn0E/edit?pli=1#heading=h.ebjj3ro0unxn).

[Committed to the GOV.UK Design System website in this pull request](https://github.com/alphagov/govuk-design-system/pull/2995).

**Comment by CharlotteDowns** [comment]
We've also added some [component specific usability information to the file upload component](https://github.com/alphagov/govuk-design-system/pull/2996)

**Comment by CharlotteDowns** [comment]
### We have now received [DAC Accessibility Report WCAG 2.2 GOV.UK Design System 17-05-2023 in a read-only.docx format](https://github.com/alphagov/govuk-frontend/files/13295096/DAC.Accessibility.Report.WCAG.2.2.GOV.UK.Design.System.17052023.Final.Read-only.docx).
