### ISSUE TITLE
Design and development updates following DAC audit

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#3946]
## What

Make any design or code updates that we've decided to make following the output of alphagov/govuk-frontend#3329.

The audit placed issues into one of two groups: WCAG-related and usability-related. WCAG issues almost certainly require a response of some kind on our part. Usability issues are more subjective, and we may choose to defer or not make changes.

## Why

Ensure that Frontend is accessible via compliance with the current WCAG 2.2 specification.

Rectify any usability issues also recorded during user testing during the audit, where we decide changes are valuable.

## Epic lead
@CharlotteDowns 

## Who needs to work on this

- Developers
- Designers
- Accessibility specialist

## Who needs to review this

- Developers
- Designers
- Accessibility specialist

## Done when

```[tasklist]
### WCAG 2.2 issues raised
- [ ] https://github.com/alphagov/govuk-frontend/issues/3839
- [ ] https://github.com/alphagov/govuk-frontend/issues/3841
- [ ] https://github.com/alphagov/govuk-frontend/issues/3846
```

```[tasklist]
### Usability issues raised
- [ ] https://github.com/alphagov/govuk-frontend/issues/3673
- [ ] https://github.com/alphagov/govuk-frontend/issues/3674
- [ ] https://github.com/alphagov/govuk-frontend/issues/3679
- [ ] https://github.com/alphagov/govuk-frontend/issues/3682
- [ ] https://github.com/alphagov/govuk-frontend/issues/3684
- [ ] https://github.com/alphagov/govuk-frontend/issues/3685
- [ ] https://github.com/alphagov/govuk-frontend/issues/3686
- [ ] https://github.com/alphagov/govuk-design-system/issues/3021
- [ ] https://github.com/alphagov/govuk-frontend/issues/3688
- [ ] https://github.com/alphagov/govuk-frontend/issues/3689
- [ ] https://github.com/alphagov/govuk-frontend/issues/3693
- [ ] https://github.com/alphagov/govuk-frontend/issues/3695
- [ ] https://github.com/alphagov/govuk-frontend/issues/3696
```

```[tasklist]
### Spin-off tasks
- [ ] https://github.com/alphagov/govuk-design-system/issues/3007
```

**Comment by querkmachine** [comment]
Calling this done. 

#3839 is going to spin-off into a separate stream of work to tie into a general investigation into our focus styles and how we use them. #3682 and #3687 have become updates to guidance and are now part of a new epic: 
- #4038

**Comment by CharlotteDowns** [comment]
Taking it out of done as the new 'Spin-off' cards relate to completing this Epic, I'm happy to take over the 'Epic lead' batten to finish off these other bits.

**Comment by davidc-gds** [comment]
@CharlotteDowns should we append the tasklists here with the content pieces from this list of `audit May 2023` labelled issues as well?
https://github.com/alphagov/govuk-design-system/issues?q=label%3A%22audit+may+2023%22+sort%3Acreated-asc

**Comment by davidc-gds** [comment]
Ohh this is the design & dev card, not the content card. Ignore my prior question. 🧠

**Comment by CharlotteDowns** [comment]
The spin off tasks have been moved to a new epic so closing again
