### ISSUE TITLE
Ensure that v5 works with the Prototype Kit

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#3947]
## Done when

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-frontend/issues/3972
- [ ] https://github.com/alphagov/govuk-frontend/issues/3759
- [ ] https://github.com/alphagov/govuk-frontend/issues/3484
```

**Comment by colinrotherham** [comment]
Going to close this one with everything working in fresh prototypes 🙌

The Prototype Kit has a couple of backwards compatibility issues still. For example, older prototypes that don't expect `window.GOVUKFrontend` to be deferred in classic `<script>` tags

* https://github.com/alphagov/govuk-prototype-kit/issues/2293
