### ISSUE TITLE
Update how Design System and Frontend Docs consume GOV.UK Frontend

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-frontend#4018]
## What

Update our own websites to match our new recommendations for loading JavaScript and use the branch deployments to test out preview/pre-releases of our changes to `govuk-frontend`.

Each of the repositories will have a "staging" `release/5.0` branches gathering all the v5.0 updates. These branches also provide a Netlify preview for us to check our all the merged changes so far:
- [Design System preview](https://release-5-0--govuk-design-system-preview.netlify.app/) – [PR](https://github.com/alphagov/govuk-design-system/pull/2977)
- [Frontend Docs preview](https://release-5-0--govuk-frontend-docs-preview.netlify.app/) – [PR](https://github.com/alphagov/govuk-frontend-docs/pull/333)

To test a new pre-release we will:
- open a PR (say on a `preview/5.0.0-alpha.X` branch) to merge a version update of GOV.UK Frontend and do any adjustment for breaking changes, pointed at `release/5.0`
- review that PR and fix any bugs noticed in the review
- once bugs have been squashed, merge the branch into `release/5.0`

## Why

5.0 changes our recommendations for loading GOV.UK Frontend's JavaScript. We need to update our own websites to match these new recommendations.

Our websites also allow us to try out our changes before releasing them to a wider audience, so we want to take advantage of that.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

```[tasklist]
### Design System site
- [ ] https://github.com/alphagov/govuk-design-system/pull/2958
- [ ] https://github.com/alphagov/govuk-design-system/pull/2976
- [ ] https://github.com/alphagov/govuk-design-system/pull/2959
- [ ] https://github.com/alphagov/govuk-design-system/pull/2960
- [ ] https://github.com/alphagov/govuk-design-system/pull/2961
```

```[tasklist]
### Frontend docs
- [ ] https://github.com/alphagov/govuk-frontend-docs/pull/318
- [ ] https://github.com/alphagov/govuk-frontend-docs/pull/334
- [ ] https://github.com/alphagov/govuk-frontend-docs/pull/335
```

**Comment by romaricpascal** [comment]
Closing at it's all done
