### ISSUE TITLE
Update the crown

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-frontend#4019]
## What

Update all relevant elements, repos and other resources that use GOV.UK Frontend, or are resources that the Design System supports. with the new crown. 

## Why

Taken from guidance provided by Government Communication Service:

> With the death of Queen Elizabeth II and the accession of King Charles III, there have been changes to the symbols used to represent the state.
> 
> The College of Arms will be preparing a new rendering of the entire royal coat of arms. No action should be taken at this stage in the use of the coat of arms.
> 
> Organisations should consider the following principles when deciding to introduce any new symbol of state:
> - Adopt a low-cost approach to implementation, avoiding wastage wherever possible
> - Begin by changing digital versions, where there is no or low associated cost
> - Physical depictions of the royal crown or cypher should only be changed at no or low cost or if truly necessary
> 
> The Cabinet Office is not placing a timeline on when symbols should be changed; it is for organisations to make decisions based on the above principles.
> 
> It is important to obtain authorisation before using any symbols of the state.

## Who needs to work on this

Interaction designer, developer.

## Who needs to review this

Product manager, interaction designer, lead frontend developer, accessibility specialist.

```[tasklist]
### Done when
- [ ] https://github.com/alphagov/govuk-frontend/issues/4057
- [ ] https://github.com/alphagov/govuk-frontend/issues/4174
- [ ] https://github.com/alphagov/govuk-frontend/issues/4175
- [ ] https://github.com/alphagov/govuk-frontend/issues/4058
- [ ] https://github.com/alphagov/govuk-frontend/issues/1739
- [ ] https://github.com/alphagov/govuk-frontend/issues/4407
- [ ] https://github.com/alphagov/govuk-frontend/issues/4179
- [ ] https://github.com/alphagov/govuk-frontend/issues/4440
- [ ] https://github.com/alphagov/govuk-frontend/issues/4178
- [ ] https://github.com/alphagov/govuk-frontend/issues/4441
- [ ] https://github.com/alphagov/govuk-frontend/issues/4059
- [ ] https://github.com/alphagov/govuk-frontend/issues/4105
- [ ] https://github.com/alphagov/govuk-frontend/issues/4620
- [ ] https://github.com/alphagov/govuk-frontend/issues/4621
- [ ] https://github.com/alphagov/govuk-design-system/issues/3423
```

**Comment by stevenjmesser** [comment]
Will scope this with @36degrees and @christopherthomasdesign next week.

**Comment by paulrobertlloyd** [comment]
Oh, I was wondering if such a change was going to happen. Is there a plan to update the Royal Coat of Arms in the footer too, as that also uses St. Edward's crown.

Related question: does the Royal Coat of Arms need to be in the footer at all?

**Comment by paulrobertlloyd** [comment]
Sorry, missed this part:

> The College of Arms will be preparing a new rendering of the entire royal coat of arms. No action should be taken at this stage in the use of the coat of arms.

Still be curious about the needs around including the arms, and whether it's need relates to Crown Copyright.

**Comment by querkmachine** [comment]
Questions we still need to answer (from memory, feel free to add).

In my mind, it's a given that we want to update the crown assets in v4 and v5, for both the one in the header and in favicon/sharing graphics. 

* What versions of Frontend do we want to do a release for?
* Should the crown graphic in the header be behind a feature flag?
  * If so, should that feature flag be turned on by default for v5.x? 
* Should we change what favicon/sharing image formats we ship with frontend to make use of manifest files and (potentially) remove older formats (e.g. Windows 8 tile icons)?
  * If so, should the changes to favicons/sharing images be included in pre-v5.x versions?
  * If so, should they be feature flagged? 
* Which crown should be used on the Design System examples during the transition period?
* Do we want to produce a new graphic lockup that incorporates the GOV.UK text into it?
  * If so, what versions of Frontend do we do this for?
  * If so, How might we need to change the 'product name' option to accommodate a new lockup?

We also have some general questions around the 'how' of feature flags, documented in #4086.

**Comment by stevenjmesser** [comment]
> Sorry, missed this part:
> 
> > The College of Arms will be preparing a new rendering of the entire royal coat of arms. No action should be taken at this stage in the use of the coat of arms.
> 
> Still be curious about the needs around including the arms, and whether the need relates to Crown Copyright.

That might be answered by the [latest newsletter from the College of Arms](https://www.college-of-arms.gov.uk/news-grants/newsletter/item/214-april-2023-newsletter-no-71) or their news about the [cypher of King Charles III](https://www.college-of-arms.gov.uk/news-grants/news/item/205-royal-cypher).

**Comment by paulrobertlloyd** [comment]
Not sure it is… and in fact my query is unrelated to who might be the current monarch and the particular design of their Royal Coat of Arms!

I’m more curious as to the needs for showing the arms is; is it a requirement of all government communications, does it relate to the Crown Copyright statement below (and again is pairing the 2 a requirement) or does it exist to reassure the public that this is an official government website…

Really am wondering if there’s an opportunity to remove the Royal Coat of Arms image entirely.

**Comment by stevenjmesser** [comment]
> Not sure it is… and in fact my query is unrelated to who might be the current monarch and the particular design of their Royal Coat of Arms!
> 
> I’m more curious as to the needs for showing the arms is; is it a requirement of all government communications, does it relate to the Crown Copyright statement below (and again is pairing the 2 a requirement) or does it exist to reassure the public that this is an official government website…
> 
> Really am wondering if there’s an opportunity to remove the Royal Coat of Arms image entirely.

I'm not sure on the reasoning or the history of decisions off the top of my head, it's one I could look into if important. What are the reasons for removing the Royal Coat of Arms?

**Comment by paulrobertlloyd** [comment]
> What are the reasons for removing the Royal Coat of Arms?

Brace yourself, I have a few! All minor, but perhaps greater than the sum of its parts…

## What value does displaying the Royal Coat of Arms in the footer provide?

Let’s start with user needs. What are they in relation to this design element? Does it provide reassurance that GOV.UK is an official communications channel? If that was the case in 2012, is it still true today? Perhaps such reassurance is already conveyed by the GOV.UK brand in the header? That it is shown in the footer perhaps gives some indication to its importance!

## Performance

In #3873, @querkmachine was concerned about [the performance overhead of serving a bitmap graphic to users](https://github.com/alphagov/govuk-frontend/pull/3873#issuecomment-1667530226). That was in relation to replacing the 2 separate images needed for different pixel densities with one, but there’s no greater performance gain than not serving an asset in the first place!

## Fewer hard coded elements within the footer

There are a few hard-coded elements in `govukFooter` that are not always relevant to service teams. The first is the OGL licence; this often makes little sense on transactional services with little or no guidance. I have removed this in the past (see [Apply for teacher training](https://www.apply-for-teacher-training.service.gov.uk/candidate/account)).

The second is the Royal Coat of Arms. Having this present reduces the amount of space available for navigation or contact information (see [Submit social housing lettings and sales data](https://submit-social-housing-lettings-sales-data.service.gov.uk/)).

## Relevance to a service/organisation

For internal services, executive agencies or arms-lengths bodies, showing the Royal Coat of Arms may make even less sense. For example:

* [Ofqal’s Register of Regulated Qualifications service](https://register.ofqual.gov.uk) replaces the arms with their own logo and that of another organisation, CEA.
* [The NHS Design System, forked from the GOV.UK Design System, forgoes the arms in their footer](https://service-manual.nhs.uk/design-system/components/footer).
* [The Home Office Design System doesn’t show the arms in their footer](https://design.homeoffice.gov.uk/components?name=Footer). Different code base, sure, but it shares a similar design which hopefully proves the broader need.

For other bodies adopting GOV.UK Frontend (local councils, other public sector bodies), the footer often needs to be adapted or replaced given these fixed elements, not least to remove the coat of arms.

## Maintenance cost

Finally, the coat of arms comes with a small amount of maintenance overhead. It’s the only bitmap graphic provided by GOV.UK Frontend as it is too complex to serve as an SVG. 

Currently 2 separate images are required, as well as a Sass mixin to account for serving these to users with different screen resolutions. (Again, see #3873)

And, on the occasion when the Royal Coat of Arms changes (hopefully not again for a few more years), it is yet another asset that needs to be updated and potentially back ported etc.

***

I guess my underlying point here is that, if the time has come when the Royal Coat of Arms in the footer component needs to be replaced, a very sensible, welcome and easier option may be to just remove it entirely.

**Comment by stevenjmesser** [comment]
Thanks @paulrobertlloyd. Do you have recommendations for adding guidance about licensing and copyright choices to the docs for teams? If we provide options, we should explain the options and what they mean. 

Also, how much effort is it for service teams to remove the Crown copyright notice? We have to weigh that up against other time-saving, effort-reducing changes we could make.

**Comment by querkmachine** [comment]
I think we're at the point where we want to switch tack to [the modified release plan mentioned in this comment](https://github.com/alphagov/govuk-frontend/issues/4174#issuecomment-1742963276), as we still don't have a concrete go-live for the new crown and v5 is speeding towards release readiness. 

I'm going to add and update some issues to accommodate it.

**Comment by querkmachine** [comment]
Does this need moving out of the 4.8 milestone? It has some things that extend well beyond the life of that particular release.

**Comment by 36degrees** [comment]
The only thing that remains in this epic is cleanup we can't do until v6.0. I don't think it's useful to keep this issue open just because for that, especially as we'll track it with the v6.0 milestone, so I'm going to call this done.
