### ISSUE TITLE
Create Password input component to help teams meet WCAG 2.2

### ISSUE THREAD

**Issue by dav-idc** [alphagov/govuk-frontend#4063]
## What
Bring in a new variant for passwords that includes a 'show / hide' control.

## Why
WCAG 2.2 success criterion '[Accessible Authentication (minimum)](https://www.w3.org/TR/WCAG22/#accessible-authentication-minimum)' states that:

> "A [cognitive function test](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum.html#dfn-cognitive-function-test) (such as remembering a password or solving a puzzle) is not required for any step in an authentication [process](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum.html#dfn-process)..." 

The understanding document also gives [specific advice in the understanding document](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum.html#hiding-content) around showing passwords in password fields:

> **Hiding characters**
> Another factor that can contribute to cognitive load is hiding characters when typing. Although this criterion requires that users do not have to type in (transcribe) a password, there are scenarios where that is necessary such as creating a password to be saved by a password manager. Providing a feature to optionally show a password can improve the chance of success for some people with cognitive disabilities or those who have difficulties with accurately typing.

## Epic lead
Beeps

## Who needs to work on this
Developer(s), designer(s), accessibility specialist, our community

## Who needs to review this
accessibility specialist

```[tasklist]
## Kick-off
- [x] Assign an epic lead
- [ ] https://github.com/alphagov/govuk-frontend/issues/4090
- [ ] https://github.com/alphagov/govuk-frontend/issues/4153
- [ ] https://github.com/alphagov/govuk-design-system/issues/3092
```

```[tasklist]
### Discovery and alpha
- [ ] https://github.com/alphagov/govuk-frontend/issues/4222
- [ ] https://github.com/alphagov/govuk-frontend/issues/4225
- [ ] https://github.com/alphagov/govuk-frontend/issues/4512
- [ ] https://github.com/alphagov/govuk-design-system/issues/3353
- [ ] https://github.com/alphagov/govuk-design-system/issues/3352
- [ ] Consider how to resolve the accessibility issue flagged here: https://github.com/alphagov/govuk-design-system/issues/2795
- [ ] https://github.com/alphagov/govuk-frontend/issues/4290
- [ ] Run a crit with DI team and original contributor
```

```[tasklist]
### Delivery
- [ ] Run a manual accessibility test (with the spreadsheet) and ensure that it meets the Success Criteria for WCAG 2.2 Accessible Authentication
- [ ] Finalise implementation of the component and write unit tests
- [ ] Create guidance
- [ ] Publish!
```

**Comment by owenatgov** [comment]
Some initial inter-team discourse on this so far:

- Whilst we should still investigate existing show/hide implementations, working off of the [show password contribution](https://github.com/alphagov/govuk-design-system-backlog/issues/240) is a good bet. This has been extensively researched for the GOV.UK Account initial launch and is being used across Digital Identity/OneLogin services, which have themselves gone through user research with this component in.
- We should think about how we should present this component in guidance. Currently, the leaning is to have a password component which includes a show password button and retain the [password pattern](https://design-system.service.gov.uk/patterns/passwords/) for guidance on best practice for storing and handling passwords. Regardless of what we choose, we should review the password pattern content in response to this component.
- We should put together a contribution group of interested parties. As this is being used significantly within GDS, there's an opportunity to work more directly with GDS colleagues to build this. Some options for a contribution group:
    - The original contributor
    - Frontend devs within Digital Identity
    - Designers within Digital Identity
- As part of this, we should cross reference our implementation and guidance with [NSCS's guidance on passwords](https://www.ncsc.gov.uk/search?q=passwords&articleType=guidance&writtenFor=Public+sector) to make sure we're compliant

**Comment by CharlotteDowns** [comment]
There has been [a conversation about the necessity of confirm password input fields](https://github.com/alphagov/govuk-design-system/pull/2861#discussion_r1250480464) in the [Add guidance on show/hide password buttons #2861](https://github.com/alphagov/govuk-design-system/pull/2861) pull request that may be worth considering as part of this work.

**Comment by dav-idc** [comment]
[David's departing thoughts]:

Given the capacity on the team and an addition of new dev and design tickets for the main WCAG 2.2 work, I'd recommend pausing this now until after the WCAG 2.2 release is all planned out. Shouldn't be too long of a delay.

Here's the GitHub issue which I believe to be higher priority. In the 'WCAG 2.2 issues to resolve', there's a list of content, design and dev issues that need to be resolved before the WCAG 2.2 release can happen.
- https://github.com/alphagov/govuk-frontend/issues/4347

**Comment by 36degrees** [comment]
Superseded by https://github.com/alphagov/govuk-design-system/issues/3454
