### ISSUE TITLE
Implement the new crown assets in Frontend (v4)

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#4179]
## What

Implement the new crown assets in new releases of GOV.UK Frontend v4.x. 

v4 will support both the original (St. Edward's) and new (Tudor) crown graphics. v4 will continue to use the St Edward's crown by default to avoid unexpected breaking changes, with teams having to explicitly opt-in to using the Tudor crown graphics.

## Why

To ensure that teams can easily impement the new GOV.UK branding into existing services.

## Who needs to work on this

- Developers

## Who needs to review this

- Developers
- Designers
- Accessibility specialist

## Done when

```[tasklist]
### Tasks
- [x] Inline SVG crown has been implemented in Header component
- [x] Fallback PNG crown has been implemented in Header component
- [x] Nunjucks and Sass feature flags to enable Tudor crown graphics have been implemented
- [x] Tudor crown favicon and web sharing graphics have been updated
```

**Comment by stevenjmesser** [comment]
Merging and releasing this is dependent on https://github.com/alphagov/govuk-frontend/issues/4059.
