### ISSUE TITLE
Reduce remaining test flakiness

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4223]
## What

Track CI (or local) recurring test issues that disappear when tests are re-run and gradually fix them as and when we can.

## Why

Flaky tests make us lose time by having to keep and eye on CI and re-run workflows. They also lower our confidence that tests passing locally will also pass on CI (or that the source of a test failure locally is due to actual changes in code).

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-frontend/issues/4169
- [ ] https://github.com/alphagov/govuk-frontend/issues/4224
- [x] https://github.com/alphagov/govuk-frontend/pull/4245
```

**Comment by colinrotherham** [comment]
Added another ad-hoc task for Windows tests that sometimes run a bit slow

For example, running the component tests with:

```shell
npx jest --color --coverage=false --maxWorkers=1 --selectProjects "JavaScript component tests"
```

Often outputs ([see example](https://github.com/alphagov/govuk-frontend/actions/runs/6261933084/job/17003196500)) the following:

```console
Running one project: JavaScript component tests

Server has taken more than 15000ms to start.

☝️ You can set "server.launchTimeout" in jest-puppeteer.config.js
Error: Process completed with exit code 1.
```

**Comment by colinrotherham** [comment]
Going to move this to Done and keep the link checker improvements separate:

* https://github.com/alphagov/govuk-design-system/issues/3113
