### ISSUE TITLE
Remove legacy crown assets from Frontend (v6.0)

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#4441]
## What

Remove remaining instances of St. Edward's crown from GOV.UK Frontend.

## Why

These assets are no longer needed, having been superceded by the Tudor crown.

## Who needs to work on this

- Developer

## Who needs to review this

- Developer

## Done when

```[tasklist]
### Tasks
- [ ] The St. Edward's crown has been removed from the header component
- [ ] The feature flag to show St. Edward's crown has been removed
- [ ] Any remaining assets featuring the St. Edward's crown have been removed or replaced
```

**Comment by querkmachine** [comment]
Have realised that this ended up being duplicated. Closing this in favour of the newer issue as it contains more details. #4623
