### ISSUE TITLE
Release v5

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4514]
## What

Prepare and release GOV.UK Frontend v5

## Why

So it can be used in production by services.

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

## Done when

```[tasklist]
### Before we release
- [x] Ensure all work in the [GOV.UK Frontend milestone](https://github.com/alphagov/govuk-frontend/milestone/46) has been completed/is ready to go
- [x] Ensure all work in the [GOV.UK Design system milestone](https://github.com/alphagov/govuk-design-system/milestone/16) has been completed/is ready to go
- [x] Ensure all work in the [GOV.UK Frontend docs milestone](https://github.com/alphagov/govuk-frontend-docs/milestone/9) has been completed/is ready to go
- [ ] https://github.com/alphagov/govuk-frontend/issues/3775
- [ ] https://github.com/alphagov/govuk-frontend/issues/4369
- [ ] https://github.com/alphagov/govuk-frontend/issues/4521
```

```[tasklist]
### Release
- [ ] https://github.com/alphagov/govuk-frontend/issues/4515
- [ ] https://github.com/alphagov/govuk-design-system/issues/3339
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/388
```

```[tasklist]
### After the release
- [x] Post [Comms](https://github.com/alphagov/govuk-frontend/issues/4369) to the relevant channels
- [x] Close the [GOV.UK Frontend milestone](https://github.com/alphagov/govuk-frontend/milestone/46)
- [x] Close the [GOV.UK Design System milestone](https://github.com/alphagov/govuk-design-system/milestone/16)
- [x] Close the [GOV.UK Frontend docs milestone](https://github.com/alphagov/govuk-frontend-docs/milestone/9)
- [x] Tidy up [the project board](https://github.com/orgs/alphagov/projects/53/)
- [ ] https://github.com/alphagov/govuk-design-system/issues/3129#issuecomment-1829982470
- [x] Have a rest
```

**Comment by 36degrees** [comment]
Considering this done 🎉
