### ISSUE TITLE
Release GOV.UK Frontend v5.1.0

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-frontend#4581]
## What
Release a new version of GOV.UK Frontend.

## Why
To release the new crown logo.

## Who needs to work on this
Developers, Tech writers, Content designers

## Done when
```[tasklist]
- [ ] https://github.com/alphagov/govuk-frontend/issues/4580
- [ ] https://github.com/alphagov/govuk-frontend/issues/4583
- [ ] https://github.com/alphagov/govuk-frontend/issues/4582
- [ ] https://github.com/alphagov/govuk-design-system/issues/3388
- [ ] https://github.com/alphagov/govuk-frontend/issues/4584
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/411
```
