### ISSUE TITLE
Release GOV.UK Frontend v5.2.0

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-frontend#4696]
## What
Release a new version of GOV.UK Frontend.

## Why
In order to release [an initial version of the new typography scale to users](https://github.com/alphagov/govuk-design-system/issues/3456).

## Who needs to work on this
Developers, Tech writers, Content designers

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-frontend/issues/4697
- [ ] https://github.com/alphagov/govuk-frontend/issues/4698
- [ ] https://github.com/alphagov/govuk-frontend/issues/4699
- [ ] https://github.com/alphagov/govuk-design-system/issues/3489
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/422
- [ ] https://github.com/alphagov/govuk-frontend/issues/4700
```
