### ISSUE TITLE
Release GOV.UK Frontend v4.8.0

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#4719]
## What
Release a new version of GOV.UK Frontend v4 with Tudor Crown support.

## Why
To release the new crown logo.

## Who needs to work on this
- Developers
- Tech writers
- Content designers

## Done when

```[tasklist]
### Tasks
- [x] Create release notes for v4.8.0
- [x] Draft comms for v4.8.0
- [x] Release Frontend v4.8.0 to npm
- [x] v4.8.0 post-release tidy-up and comms
```
