### ISSUE TITLE
Release GOV.UK Frontend v3.15.0

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#4720]
## What
Release a new version of GOV.UK Frontend v3 with Tudor Crown support.

## Why
To release the new crown logo.

## Who needs to work on this
- Developers
- Tech writers
- Content designers

## Done when

```[tasklist]
### Tasks
- [x] Create release notes for v3.15.0
- [x] Draft comms for v3.15.0
- [x] Release Frontend v3.15.0 to npm
- [x] v3.15.0 post-release tidy-up and comms
```
