### ISSUE TITLE
Release GOV.UK Frontend v5.3.0

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#4874]
## What

Release a new version of GOV.UK Frontend.

## Why

To release the new password input component and latest bugfixes.

## Who needs to work on this

- Developers
- Tech writer
- Content designer

## Done when

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-frontend/issues/4875
- [ ] https://github.com/alphagov/govuk-frontend/issues/4876
- [ ] https://github.com/alphagov/govuk-frontend/issues/4877
- [ ] https://github.com/alphagov/govuk-frontend/issues/4878
- [ ] https://github.com/alphagov/govuk-frontend/issues/4879
- [ ] https://github.com/alphagov/govuk-frontend/issues/4880
```
