### ISSUE TITLE
Create release notes for v5.3.0

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#4876]
## What

Create release notes for Frontend v5.3.0.

## Why

So that users are aware of what features have been added, what bugfixes have been made, and what features have been deprecated.

## Who needs to work on this

- Content designer
- Tech writer
- Developers

## Who needs to review this

- Developers

## Done when

```[tasklist]
### Tasks
- [x] Release notes have been drafted
- [x] Release notes have been 2i'd
- [x] A pull request has been opened to update the changelog
```
