### ISSUE TITLE
Update the Design System website to use Frontend v5.3.0

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#4878]
## What

Update the Design System website to use Frontend v5.3.0.

## Why

So that the Design System reflects the current version of Frontend.

## Who needs to work on this

- Developers

## Who needs to review this

- Developers

## Done when

```[tasklist]
### Tasks
- [x] The Design System website is using GOV.UK Frontend v5.3.0
- [x] The "What's New" section of the homepage has been updated
- [x] The "Recently shipped" section of the Roadmap page has been updated
- [x] Any guidance changes relating to v5.3.0 features have been merged
- [x] Any other pull requests dependent on v5.3.0 have been merged
```
