### ISSUE TITLE
Post-release tidy up and comms for v5.3.0

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#4880]
## What

Complete the release of GOV.UK Frontend v5.3.0.

## Why

Keep things tidy. 🧹 

## Who needs to work on this

- Content designer
- Tech writer
- Developers

## Who needs to review this

- Anyone on the team

## Done when

```[tasklist]
### Tasks
- [x] Comms have been released to all relevant channels: #4875
- [x] The v5.3.0 GitHub milestone has been closed in Frontend, Design System and Frontend Docs repos
- [x] The project board has been updated
```
