### ISSUE TITLE
Prepare expansion of public JavaScript API of GOV.UK Frontend

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#5144]
## Brief

Design public JavaScript features to be provided by GOV.UK Frontend, both for interacting with components (methods, events, callbacks) and for building components that do not exist in GOV.UK Frontend.

Plan the documentation of such features in [the Frontend docs site](https://frontend.design-system.service.gov.uk/).

As a stretch, start strenghtening components initialisation so that:
- components error if initialised twice on the same element
- existing component instances can be obtained for a given component

## Epic lead

Romaric

## Driving role(s)

Developers, Technical writer

## Supporting roles

N/A

## Needs awareness

N/A

## Further detail

```[tasklist]
### Design a public API
- [ ] https://github.com/alphagov/govuk-frontend/issues/5148
- [ ] https://github.com/alphagov/govuk-frontend/issues/5149
- [ ] https://github.com/alphagov/govuk-frontend/issues/5151
- [ ] https://github.com/alphagov/govuk-frontend/issues/5152
- [ ] https://github.com/alphagov/govuk-frontend/issues/5173
- [ ] https://github.com/alphagov/govuk-frontend/issues/5147
- [ ] https://github.com/alphagov/govuk-frontend/issues/5174
```

```[tasklist]
### Prepare API documentation
- [ ] https://github.com/alphagov/govuk-frontend/issues/5153
- [ ] https://github.com/alphagov/govuk-frontend/issues/5155
- [ ] https://github.com/alphagov/govuk-frontend/issues/5157
```
