### ISSUE TITLE
Start expanding the library's public API

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#5205]
## Brief

Start expanding the public API of GOV.UK Frontend by opening some features for initialising components:
- checking if GOV.UK Frontend is supported in a consistent way
- initialising GOV.UK Frontend components and service components the same way
- offering a base component class checking GOV.UK Frontend support and storing the root element of components

Ensure these features are documented in the Frontend docs, with both:
- guidance on how to use them
- an API reference of the classes/functions that provide them (and their properties/methods/arguments/return values...)

This is a first step towards maintaining a wider public API both for using our components and creating components in services.

## Epic lead

@romaricpascal 

## Driving role(s)

@seaemsi, @patrickpatrickpatrick 

## Further detail

```[tasklist]
### Expanding the API
- [ ] https://github.com/alphagov/govuk-frontend/issues/5209
- [ ] https://github.com/alphagov/govuk-frontend/issues/5210
- [ ] https://github.com/alphagov/govuk-frontend/issues/5213
- [ ] https://github.com/alphagov/govuk-design-system/issues/3812
- [ ] https://github.com/alphagov/govuk-frontend/issues/5211
- [ ] https://github.com/alphagov/govuk-frontend/issues/5212
- [ ] https://github.com/alphagov/govuk-frontend/issues/5214
- [ ] [Stretch] https://github.com/alphagov/govuk-frontend/issues/1127
- [ ] https://github.com/alphagov/govuk-frontend/issues/5267
- [ ] https://github.com/alphagov/govuk-frontend/issues/5216
- [ ] https://github.com/alphagov/govuk-frontend/issues/5217
- [ ] https://github.com/alphagov/govuk-frontend/issues/5225
- [ ] https://github.com/alphagov/govuk-frontend/issues/5215
```

```[tasklist]
### Documenting the API
- [ ] https://github.com/alphagov/govuk-frontend/issues/5224
- [ ] https://github.com/alphagov/govuk-frontend/issues/5226
- [ ] https://github.com/alphagov/govuk-frontend/issues/5227
- [ ] Add documentation for isSupported to the Frontend docs
- [ ] Add documentation for the updates to `createAll` to the Frontend docs
- [ ] Add documentation for the base component class to the Frontend docs
```
```[tasklist]
### Admin
- [x] Initialise decision log (based on Navigation one)
- [x] Document the state we aim for at the end of the cycle
```

**Comment by romaricpascal** [comment]
Work will carry on in #5292
