### ISSUE TITLE
Release v5.6.0

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#5271]
## What

Release a new version of GOV.UK Frontend with the latest changes we've built.

## Why

So people can use the new features and bugfixes included.

## Who needs to work on this

- Technical writers
- Developers

## Who needs to review this

- Technical writers
- Developers

## Done when

```[tasklist]
## Comms preparation
- [x] Draft release notes - see [Google doc](https://docs.google.com/document/d/1gMQujV3yaOL7DknuplKnVZDu1sh8kuhuEzETaeqgSUw/)
- [ ] https://github.com/alphagov/govuk-design-system/issues/4076
```

```[tasklist]
## GOV.UK Frontend
- [x] Service navigation component has been merged #5206
- [x] Follow [our process to release GOV.UK Frontend to npm and GitHub](https://github.com/alphagov/govuk-frontend/blob/main/docs/releasing/publishing.md)
```

```[tasklist]
## Design System site
- [x] [Run dependabot](https://github.com/alphagov/govuk-design-system/network/updates/194539/jobs) to bump the version of `govuk-frontend`
- [x] Update [the "What's new" section on the homepage](https://github.com/alphagov/govuk-design-system/blob/main/views/partials/_whats-new.njk)
- [x] Update [the "Recently shipped" section of the roadmap](https://github.com/alphagov/govuk-design-system/blob/main/src/community/roadmap/index.md#recently-shipped)
```

```[tasklist]
## Frontend docs
- [x] [Run dependabot](https://github.com/alphagov/govuk-frontend-docs/network/updates/4008122/jobs) to bump the version of `govuk-frontend`
```

```[tasklist]
## Comms
- [x] Send comms on Slack channels
- [x] Send comms to mailing list
```

```[tasklist]
- [x] Tidy up issues on GitHub
```
