### ISSUE TITLE
Get the new parts of the public API ready for publishing

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#5292]
## Brief

Wrap up the work on component initialisation (error callback for `initAll`, preventing double initialisation) and get a base component class in shape for publishing in our next release. This also includes making sure we've got the docs ready to go so we can tell people how to start using them.

## Epic lead

@romaricpascal 

## Driving role(s)

@seaemsi, @patrickpatrickpatrick 

## Supporting roles
@Izabela-16 

## Further detail

```[tasklist]
### Component initialisation
- [ ] https://github.com/alphagov/govuk-frontend/issues/5267
- [ ] https://github.com/alphagov/govuk-frontend/issues/1127
- [ ] https://github.com/alphagov/govuk-frontend/issues/5303
- [ ] https://github.com/alphagov/govuk-frontend/issues/5214
- [ ] https://github.com/alphagov/govuk-frontend/issues/5225
- [ ] [Stretch] Investigate configuration helpers
- [ ] https://github.com/alphagov/govuk-frontend/issues/5369
```

```[tasklist]
### Docs
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/462
- [ ] Add documentation for isSupported to the Frontend docs
- [ ] Add documentation for the updates to `createAll` and `initAll` to the Frontend docs
- [ ] Add documentation for the base component class to the Frontend docs
- [ ] Add documentation for the prevention of double initialisation
- [ ] https://github.com/alphagov/govuk-frontend/issues/5321
```

```[tasklist]
### Base component
- [ ] https://github.com/alphagov/govuk-frontend/issues/5323
- [ ] https://github.com/alphagov/govuk-frontend/issues/5324
- [ ] https://github.com/alphagov/govuk-frontend/issues/5325
- [ ] https://github.com/alphagov/govuk-frontend/issues/5326
- [ ] https://github.com/alphagov/govuk-frontend/issues/5327
- [ ] https://github.com/alphagov/govuk-frontend/issues/5322
- [ ] https://github.com/alphagov/govuk-design-system/issues/4156
```

**Comment by romaricpascal** [comment]
Closing, with the publishing being the first part of https://github.com/alphagov/govuk-frontend/issues/5292.
