### ISSUE TITLE
Add template for pull requests to encourage better PR structure

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#5329]
## What

Add [a pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) to the repository to guide people when raising a PR with hints about information that would be useful to provide (eg. screenshots, future works, questions that need answering), as well as reminders for code changes that might have been skipped (macro options, tests, CHANGELOG...)

## Why

Consistent PR structure would help with review, especially if we nudge towards better description of what's in the PR. 
Reminders about tests, doc changes... would help ensure the PRs contain everything that's needed for them to be merged (and avoid extra PRs to add them).

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

## Done when

- [ ] We've decided on the content for such template
- [ ] It has been added to the repository

**Comment by romaricpascal** [comment]
Quickly browsing through recent PRs (especially those of @querkmachine which are always pretty thorough and well written), here's a base structure for discussion:

- **Logistics** (optional): warning if the PR needs to wait before being merged of similar importance
- **Intro**: high level description of the problem solved by the PR. Can be enough for small PRs
- **Background/Context** (optional): if some context is needed to better understand the changes (eg. PR history)
- **Changes** (optional): List of the changes that the PR brings
- **Thoughts** (optional): Explain choices that were made in the PR and are not already described by the changes, or code/PR comments
- **Screenshots** (optional): Screenshots that would help understand the changes
- **Todo** (optional): If more work is needed to fully form the PR or as future work like:
		- questions to answer before merge
		- updates to make
		- issues to create for future work once merged
- **This PR contains**
	- [ ] Tests for the changes
	- [ ] Accessibility review
	- [ ] Documentation updates (macro options, Design System guidance, Frontend docs)
	- [ ] A CHANGELOG entry
- **Closes <ISSUE_NUMBER>** (optional)

**Comment by querkmachine** [comment]
We've had more PRs raised recently that appear to be AI/LLM generated without disclosing whether they are. Discussions in the team point towards us wanting contributors to have to explicitly disclose any LLM usage. We could probably fold that into the PR template.

**Comment by querkmachine** [comment]
To iterate on the above proposal, now that we're chatting about PR templates again, the one I currently mentally operate from goes like this.

It probably needs some amendment given our discussions about including more context around design history and decision logging; and our likely desire to expect explicit disclosure of AI/LLM usage, if we allow AI contributions at all.

---

A brief introduction providing an overview of the change.

> [!NOTE] 
> Logistics notice indicating any restrictions on merging, formatted as an [alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts). 

Issues that are related to, resolved, or closed by this PR, using [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) where appropriate. Closes #5329. 

## Background (optional)
Free text describing any further background useful for understanding the PR, such as the outcomes of research, spikes, and prior attempts to do this or something similar. 

## Changes
- Added bullet pointed list of what changes have been made.
- Rewritten to be in the past tense and starting with verbs ('added', 'removed', 'changed', etc.)
  - If a change is quite substantial or deserving of nuance, nested bullet points can be used to break things down further. 

### Screenshots (optional)
Screenshots showing any substantive visual changes. 

If there is a before and after (i.e. it's not a new addition) then these are formatted as a table. If multiple things have visually changed, such as multiple component states or different renderings across browsers, these are added as new rows to the table. 

|State  |Before        |After         |
|:------|:-------------|:-------------|
|Default||| 

## Thoughts (optional)
Free text extrapolating on any new decisions made during the creation of the PR (i.e. not part of the background), such as why a particular development approach was taken over another. 

## Todo (optional)
Bullet point or checklist of: 

- [ ] Any outstanding tasks left to do on the PR, if it's currently unfinished
- [ ] 'Leftovers' that need to be followed up on, such as raising a new issue to remove deprecated code.
