### ISSUE TITLE
Add configuration helpers to the public JavaScript API

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#5373]
## Brief

Design and document a public API to enable components outside of GOV.UK Frontend to receive a configuration in the same fashion the components from GOV.UK Frontend do. 

This will allow further code sharing between code from GOV.UK Frontend and that of services or other Design Systems, leading less duplication in the compiled bundles sent to users, as well as avoiding to recreate a solution to the problem for services and other Design Systems.

This will also open the door to offering helpers for internationalising components, which we could start looking at as a stretch goal towards the end of the epic if time allows.

### Relevant links

- [Configure components](https://frontend.design-system.service.gov.uk/configure-components/#configure-components) on the GOV.UK Frontend docs
- [`mergeConfigs` helper](https://github.com/alphagov/govuk-frontend/blob/1925ea6330d0e0acd4c2f75cdc065de6772b2b91/packages/govuk-frontend/src/govuk/common/index.mjs#L21) that helps merging configuration from different sources (defaults, HTML Element attributes, JavaScript object)
- A [spike from Ollie](https://github.com/alphagov/govuk-frontend/compare/main...wip-classes) proposing a way to [implement the configuration as a class](https://github.com/alphagov/govuk-frontend/blob/8327d7d82b54bc04d16fcd39864899b1c9db654f/src/govuk/common/config.mjs) (note that there's been some changes to how the merging of configuration works since).

## Epic lead

@romaricpascal 

## Driving role(s)

@seaemsi , @patrickpatrickpatrick, @Izabela-16 

## Further detail

```[tasklist]
### Publish new API
- [ ] https://github.com/alphagov/govuk-frontend/issues/5326
- [ ] https://github.com/alphagov/govuk-design-system/issues/4156
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/467
- [x] Merge `public-js-api` to `main`
- [x] Check no further refactoring of `$module` to `$root` are necessary (https://github.com/alphagov/govuk-frontend/issues/5322)
- [x] Release
- [x] Close alphagov/govuk-frontend#1127
- [ ] https://github.com/alphagov/govuk-frontend-docs/pull/472
- [x] Update workaround for TypeScript
```

```[tasklist]
### Dev
- [x] https://github.com/alphagov/govuk-frontend/pull/5427
- [x] https://github.com/alphagov/govuk-frontend/pull/5426
- [x] https://github.com/alphagov/govuk-frontend/pull/5430
- [ ] https://github.com/alphagov/govuk-frontend/issues/5456
- [ ] https://github.com/alphagov/govuk-frontend/issues/5457
- [ ] https://github.com/alphagov/govuk-frontend/issues/5458
- [ ] https://github.com/alphagov/govuk-frontend/issues/5459
- [ ] https://github.com/alphagov/govuk-frontend/issues/5460
- [ ] https://github.com/alphagov/govuk-frontend/issues/5461
- [ ] https://github.com/alphagov/govuk-frontend/issues/5462
- [ ] https://github.com/alphagov/govuk-frontend/issues/5463
- [ ] https://github.com/alphagov/govuk-design-system/issues/4275
- [ ] https://github.com/alphagov/govuk-frontend/issues/5497
- [ ] https://github.com/alphagov/govuk-frontend/issues/5469
- [ ] https://github.com/alphagov/govuk-frontend/issues/5465
- [ ] https://github.com/alphagov/govuk-frontend/issues/5466
- [ ] https://github.com/alphagov/govuk-frontend/issues/5468
- [ ] https://github.com/alphagov/govuk-design-system/issues/4276
```

```[tasklist]
### Documentation
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/482
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/483
- [ ] https://github.com/alphagov/govuk-frontend/issues/5502
- [ ] https://github.com/alphagov/govuk-frontend/issues/5501
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/486
- [ ] Merge the content to the main branch of the Frontend docs
```
```[tasklist]
### Community
- [ ] https://github.com/alphagov/govuk-frontend/issues/5472
- [ ] https://github.com/alphagov/govuk-frontend/issues/5506
```

**Comment by romaricpascal** [comment]
A couple of thoughts:

- Not all components accept a configuration, so we need the feature to be composable rather than baked into the `Component` class that all components will inherit, and especially able to be tree-shaken if not used. If some steps in the feature are optional, it'd be neat if they can be tree-shaken when not used, as well. However, there'll be a balance to strike between something monolithic that encapsulates all steps, ensuring they run in the right order, and something more fragmented leaving it to the user to run each step but where unnecessary steps can be left out of the bundled code.
- Some of our components do [validations on the configuration they receive](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk/common/index.mjs#L236). We'll need to check how costly it would be to offer this as part of the public API as it could quickly spin into lots of Kbs that services can already use a 3rd party package to handle themselves (we have to implement ours to remain dependency free for now)
- Most components do a straightforward merge of configuration options from their defaults, HTML dataset and constructor argument. [The Character Count needs to do some overriding](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs#L93-L99) which we'll need to account for.
    - I _think_ that's the only component with such shenanigans in GOV.UK Frontend, but it's worth a double check
    - Components outside GOV.UK Frontend may need a similar thing where the presence of one or multiple options in the constructor argument may mean some option(s) from the defaults or HTML dataset need clearing up.
- as always, we'll be the first consumer of our feature, so it's good to look at the components in the Design System and see if any can be configured one way or another (the [Cookie banner looks like it could](https://github.com/alphagov/govuk-design-system/blob/main/src/javascripts/components/cookie-banner.mjs#L43-L44))

**Comment by romaricpascal** [comment]
Closing this as the final non-stretch issue has a PR almost ready to go (only missing a changelog entry) and the stretch issue can be tackled anytime.
