### ISSUE TITLE
Release v5.7.0

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#5386]
## What

Release a new version of GOV.UK Frontend with the latest changes we've built.

## Why

So people can use this new version

## Who needs to work on this

Technical writers, Developers

## Who needs to review this

Technical writers, Developers

## Done when

```[tasklist]
## Comms preparation
- [x] Draft release notes
- [x] Draft comms
```

```[tasklist]
## GOV.UK Frontend
- [x] Follow [our process to release GOV.UK Frontend to npm and GitHub](https://github.com/alphagov/govuk-frontend/blob/main/docs/releasing/publishing.md)
```

```[tasklist]
## Design System site
- [x] [Run dependabot](https://github.com/alphagov/govuk-design-system/network/updates/194539/jobs) to bump the version of `govuk-frontend`
- [x] Update [the "What's new" section on the homepage](https://github.com/alphagov/govuk-design-system/blob/main/views/partials/_whats-new.njk)
- [x] Update [the "Recently shipped" section of the roadmap](https://github.com/alphagov/govuk-design-system/blob/main/src/community/roadmap/index.md#recently-shipped)
```

```[tasklist]
## Frontend docs
- [x] [Run dependabot](https://github.com/alphagov/govuk-frontend-docs/network/updates/4008122/jobs) to bump the version of `govuk-frontend`
- [x] Merge the PR for https://github.com/alphagov/govuk-frontend-docs/issues/467
```

```[tasklist]
## Comms
- [x] Send comms on Slack channels
- [x] Send comms to mailing list
```

```[tasklist]
- [x] Tidy up issues on GitHub
```

**Comment by romaricpascal** [comment]
5.7.0 has been released 🥳
