### ISSUE TITLE
Release v4.8.0

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#5387]
## What

Release a new version of GOV.UK Frontend with the latest changes we've built.

## Why

So people can use this new version

## Who needs to work on this

Technical writers, Developers

## Who needs to review this

Technical writers, Developers

## Done when

```[tasklist]
## Comms preparation
- [x] Draft release notes
```

```[tasklist]
## GOV.UK Frontend
- [x] Follow [our process to release GOV.UK Frontend to npm and GitHub](https://github.com/alphagov/govuk-frontend/blob/support/4.x/docs/releasing/publishing.md)
```

```[tasklist]
- [x] Tidy up issues on GitHub
```
