### ISSUE TITLE
Make enhancements to the File Upload component and prepare to ship in v5.9

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-frontend#5626]
## Brief
By the end of the brief, we should have:
- reviewed [progressively enhanced File upload component ](https://github.com/alphagov/govuk-frontend/pull/5305) and tested this with browsers and AT
- prepared component to be shipped in v5.9, planned for the end of January

We should also consider publicly documenting our decision making rationale regarding these changes on the [community backlog](https://github.com/orgs/alphagov/projects/43/views/2) or [GitHub discussions](https://github.com/alphagov/govuk-design-system/discussions).

## Issues we are trying to solve

**Dragon cannot easily activate the File upload button** alphagov/govuk-design-system#4031 
The 'Choose file' input does not respond to any verbal command. The user must then use verbal keyboard commands such as 'Tab' to use the component. Proposed solution is to layer a new UI onto the component which can be customised (eg as a button), and shows a visual drop zone if a file is dragged over it.

While that is the main issue we want to fix, because we plan to rewrite the component in a way that will make it easier to customise, the following are sensible additions that will make the component also more usable and/or accessible:

* give the upload button a GOV.UK look
* provide a visible drag 'n' drop area (which would close alphagov/govuk-frontend#3685)
* add the possibility to change the text on the button (e.g. "Choose file") and feedback (e.g. "No file chosen")

## Epic lead
Anika

## Driving role(s)
Patrick, Charlotte

## Supporting roles
Romaric, Kelly

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-frontend/issues/5613
- [ ] https://github.com/alphagov/govuk-frontend/issues/5620
- [ ] https://github.com/alphagov/govuk-frontend/issues/5611
- [ ] https://github.com/alphagov/govuk-frontend/issues/5621
- [ ] https://github.com/alphagov/govuk-frontend/issues/5612
- [ ] https://github.com/alphagov/govuk-frontend/issues/5622
- [ ] https://github.com/alphagov/govuk-frontend/issues/5615
- [ ] https://github.com/alphagov/govuk-frontend/issues/5617
- [ ] https://github.com/alphagov/govuk-frontend/issues/5616
- [ ] https://github.com/alphagov/govuk-frontend/issues/5618
- [ ] https://github.com/alphagov/govuk-frontend/issues/5619
- [ ] https://github.com/alphagov/govuk-frontend/issues/5623
- [ ] https://github.com/alphagov/govuk-frontend/issues/5644
- [ ] https://github.com/alphagov/govuk-design-system/issues/4485
- [ ] https://github.com/alphagov/govuk-frontend/issues/5614
- [ ] https://github.com/alphagov/govuk-frontend/issues/5624
- [ ] https://github.com/alphagov/govuk-frontend/issues/5680
- [ ] https://github.com/alphagov/govuk-frontend/issues/5681
- [ ] https://github.com/alphagov/govuk-frontend/issues/5682
- [ ] https://github.com/alphagov/govuk-frontend/issues/5683
- [ ] https://github.com/alphagov/govuk-frontend/issues/5684
- [ ] https://github.com/alphagov/govuk-frontend/issues/5685
- [ ] https://github.com/alphagov/govuk-frontend/issues/5686
- [ ] https://github.com/alphagov/govuk-frontend/issues/5688
- [ ] https://github.com/alphagov/govuk-frontend/issues/5689
```
